---
# tasks file for nfs_hegre_role
- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/Hegre
  register: hegre_dir
  
- name: create the mount directory, if necessary
  file:
    path:     /mnt/mobius/Hegre
    state:    directory
    recurse:  yes
  when: not hegre_dir.stat.exists

- name: Mount the pr0n NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/Hegre
    path: /mnt/mobius/Hegre
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
  