---
# tasks file for nfs_hegre_role
- name: Mount the Hegre NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/Hegre
    path: /mnt/mobius/Hegre
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
