# tasks file for git_dotfiles_role
- name: Deploy the dotfiles git repository
  git:
    # repo: 'https://github.com/educatedCaveman/dotfiles.git'
    # TODO: figure out why this isn't working
    # repo: 'https://forgejo.drak3.io/drak3/dotfiles.git'
    repo: ssh://git@git.drak3.io/drak3/dotfiles.git
    dest: /home/drake/dotfiles
    version: master
    # key_file: /home/drake/.ssh/theseus2_id_ed25519.pub
    force:  yes

# tasks file for git_scripts_role
- name: Deploy the scripts git repository
  git:
    # repo: https://github.com/educatedCaveman/scripts
    # TODO: figure out why this isn't working
    # repo: 'https://forgejo.drak3.io/drak3/scripts.git'
    repo: ssh://git@git.drak3.io/drak3/scripts.git
    dest: /home/drake/scripts
    version:  master


    