---
# tasks file for linux_role

# ZSH
- name: Configure ZSH
  import_tasks: zsh.yml

# Tmux
- name: Configure Tmux
  import_tasks: tmux.yml

# NeoVim
- name: Configure NeoVim
  import_tasks: neovim.yml

# MOTD
- name: Configure MOTD
  import_tasks: MOTD.yml

# Quality of life packages
- name: Install Quality-of-Life packages
  import_tasks: packages.yml

# timezone:
- name: set timezone
  timezone:
    name: America/New_York
    