- name: Create drake with locked password
  user:
    name: drake
    append: yes
    groups: 
      - sudo
    # update_password:  on_create
    password: 'password'
  register: accounts
  notify: force_change_password

# - name: Unlock password and set it to empty
#   command: passwd -d drake

# - name: Expire password
#   command: chage -d 0 drake

# handler
- name: force_change_password
  command: "chage -d 0 drake"
  when: accounts.exists