---
# tasks file for LXC_role
# install git, as its missing from the base image
- name: install git
  import_tasks: install_git.yml

# create drake user
- name: create drake user
  import_tasks: create_drake.yml

# copy authorized_keys file from root to drake
- name: copy authorized_keys
  import_tasks: authorized_keys.yml

# disable netdata (temp fix)
# systemd restart and enable netdata
# - name: enable and restart netdata
#   systemd:
#     name: netdata
#     state:  stopped
#     enabled:  no
