---
- name: deploy docker code to DEV portainer instance
  hosts: lv-426
  tasks:

    - name: deploy dev_test branch
      git:
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /mnt/mobius/docker
        version:  dev_test
        force:  yes

    - name: set permissions in the directory
      file:
        path: /mnt/mobius/docker
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake