---
- name: deploy ansible repo to itself
  hosts:  self
  tasks:

    # remove hosts
    - name: remove the existing hosts file
      file:
        path: /etc/ansible/hosts
        state:  absent

    # copy hosts
    - name: copy jenkins hosts to system
      copy:
        src:  "{{ jenkins_ansible }}/hosts"
        dest: /etc/ansible/hosts

    # remove config
    - name: remove the existing ansible.cfg
      file:
        path: /etc/ansible/ansible.cfg
        state:  absent

    # copy config
    - name: copy jenkins ansible.cfg to system
      copy:
        src:  "{{ jenkins_ansible }}/ansible.cfg"
        dest: /etc/ansible/ansible.cfg

    # make sure drake has the copybooks
    - name: create the ansible/ directory
      file:
        path: /home/drake/ansible
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/ansible
      register: ansible_dir

    - name: deploy ansible repo
      git:
        repo: https://github.com/educatedCaveman/ansible
        dest: /home/drake/ansible
        version:  master
        force:  yes
      when: ansible_dir.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/ansible
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake
