---
- name: deploy ansible repo to itself
  hosts:  self
  tasks:

    - name: create the ansible/ directory
      file:
        path: /home/drake/ansible
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/ansible
      register: ansible_dir

    - name: deploy ansible repo
      git:
        repo: https://github.com/educatedCaveman/ansible
        dest: /home/drake/ansible
        version:  master
        force:  yes
      when: ansible_dir.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/ansible
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake

    # # deploy system-wide config and hosts file
    # # remove existing hosts file
    # - name: remove existing ansible hosts file
    #   file:
    #     path: /etc/ansible/hosts
    #     state:  absent

    # # copy file to system location
    # - name: copy repository hosts file to system location
    #   copy:
    #     src:  /home/drake/ansible/hosts
    #     dest: /etc/ansible/hosts
    #     remote_src: yes

    # # remove existing config file
    # - name: remove existing ansible.cfg file
    #   file:
    #     path: /etc/ansible/ansible.cfg
    #     state:  absent

    # # copy file to system location
    # - name: copy repository ansible.cfg file to system location
    #   copy:
    #     src:  /home/drake/ansible/ansible.cfg
    #     dest: /etc/ansible/ansible.cfg
    #     remote_src: yes
