---
- name: deploy ansible repo to itself
  hosts:  
    - self
    - dilithium
  tasks:

    # make sure drake has the copybooks
    - name: create the ansible/ directory
      file:
        path: /home/drake/ansible
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/ansible
      register: ansible_dir

    - name: deploy ansible repo
      git:
        repo: https://github.com/educatedCaveman/ansible
        dest: /home/drake/ansible
        version:  master
        force:  yes
      when: ansible_dir.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/ansible
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake

- name: deploy ansible repo to itself
  hosts:  
    - dilithium
  tasks:

    - name: remove existing host file/link
      file:
        path: /etc/ansible/hosts.ini
        state:  absent

    - name: link new hosts file
      file:
        src:  /home/drake/ansible/hosts.ini
        dest: /etc/ansible/hosts
        state:  link

    - name: remove existing ansible.cfg file/link
      file:
        path: /etc/ansible/ansible.cfg
        state:  absent

    - name: link new ansible.cfg file
      file:
        src:  /home/drake/ansible/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        state:  link
