---
- name: deploy stack config files
  hosts:  labnodes
  tasks:

    - git: deploy github repo (dev_test branch)
      repo: 'https://github.com/educatedCaveman/docker-lab'
      refspec: 'refs/head/dev_test'
      dest: '/mnt/mobius/docker'

    #do we need to set permissions?