---
- name: deploy scripts repo to drake's /home
  hosts:  self
  tasks:

    - name: create the scripts/ directory
      file:
        path: /home/drake/scripts
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/scripts
      register: scripts_dir

    - name: deploy ansible repo
      git:
        repo: https://github.com/educatedCaveman/scripts
        dest: /home/drake/scripts
        version:  master
        force:  yes
      when: scripts_dir.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/scripts
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake