---
- name: configure NFS mounts for docker
  hosts: labnodes
  tasks:

    - name: make sure we have the nfs-utils...
      yum:
        name: nfs-utils
        state: latest

    - name: Mount the Backup share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Backup
        path: /mnt/mobius/Backup
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

    - name: Mount the staging share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/staging/docker/dev
        path: /mnt/mobius/staging
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

    - name: Mount the Docker share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Docker/dev
        path: /mnt/mobius/docker
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

