---
- name: ansible configure itself
  hosts: self
  tasks:

    # remove old hosts file
    - name: remove old hosts file/link
      file:
        path: /etc/ansible/hosts
        state:  absent

    # link new hosts file
    - name: link new hosts file
      file:
        src:  /var/lib/jenkins/workspace/ansible_master/hosts
        dest: /etc/ansible/hosts
        state:  link

    # remove old config file
    - name: remove old config file
      file:
        path: /etc/ansible/ansible.cfg
        state:  absent

    # link new config file
    - name: link new config file
      file:
        src:  /var/lib/jenkins/workspace/ansible_master/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        state:  link
