---
- name: configure rtorrent + flood
  hosts: rtorrent
  tasks:
    # make sure all packages are up to date
    - name: update packages
      apt:
        name: "*"
        state: latest

    # make sure all the required packages are installed
    - name: ensure a list of packages installed
      apt:
        name:
          - rtorrent
          - nodejs
          - curl

    # make sure the /srv/torrent/downloads directory exists
    - name: make sure the '/srv/torrent/downloads' folder exists
      file:
        path: /srv/torrent/downloads
        state:  directory
        recurse:  yes

    # make sure the /srv/rtorrent/downloads directory exists
    - name: make sure the '/srv/torrent/.session' folder exists
      file:
        path: /srv/torrent/.session
        state:  directory
        recurse:  yes

    # set permissions
    - name: set permissions on the '/srv/torrent' folder
      file:
        path: /srv/rtorrent
        state:  directory
        owner:  rtorrent
        group:  rtorrent
        mode: '0755'
        recurse:  yes

    # deploy dotfiles repo
    - git:
        repo: 'https://github.com/educatedCaveman/dotfiles.git'
        dest: /home/drake/dotfiles
        force:  yes

    # link the config file
    # remove the existing config, if present
    - name:
      file:
        path: /home/rtorrent/.rtorrent.rc
        state: absent

    # ensure the link from dotfiles is set
    - name: link the config
      file:
        src: /home/drake/dotfiles/rtorrent/rtorrent.conf
        dest: /home/rtorrent/.rtorrent.rc
        owner:  rtorrent
        group:  rtorrent
        state: link
    
    # systemd:
    # /etc/systemd/system/rtorrent.service
    - name: link the systemd file
      file:
        src: /home/drake/dotfiles/rtorrent/rtorrent.service
        dest: /etc/systemd/system/rtorrent.service
        state: link
