---
- name: configure host for NUT
  hosts: dilithium
  tasks:

    - name: update packages
      apt:
        name: '*'
        state: latest

    - name: make sure packages are installed
      apt:
        name: 
          - nut
          - nut-client
          - nut-server
          - nut-cgi
          - fcgiwrap
          - msmtp