---
- name: configure Sevastopol Docker host
  hosts: sevastopol
  tasks:

    - name: update packages
      yum:
        name: '*'
        state: latest

    - name: ensure a list of packages installed
      yum:
        name: 
          - neovim
          - neofetch
          - zsh
          - tmux
          - git
          - htop
          - nfs-utils
          - tree

    #change shell
    - name: change to ZSH
      user:
        name: drake
        shell: /usr/bin/zsh
    
    #deploy dotfiles repo
    - git:
        repo: 'https://github.com/educatedCaveman/dotfiles.git'
        dest: /home/drake/dotfiles

    #create Vundle directory, which also creates the nvim directory
    - name: create NeoVim and Vundle directories
      file:
        path: /home/drake/.config/nvim/bundle
        state: directory
        recurse: yes
    
    #Vundle
    - name: verify Vundle directory exists
      stat:
        path: /home/drake/.config/nvim/bundle
      register: stat_nvim_bundle
    
    - name: cloning Vundle
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: /home/drake/.config/nvim/bundle/Vundle.vim
      when: stat_nvim_bundle.stat.exists
    
    #oh-my-zsh
    #clone the repo 
    - name: Cloning  oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: /home/drake/.oh-my-zsh
      #when: not stat_oh_my_zsh_result.stat.exists

    - name: Check if .oh-my-zsh exists
      stat:
        path: /home/drake/.oh-my-zsh
      register: stat_oh_my_zsh_result
    
    #check if .zshrc exists:
    - name: checking for .zshrc
      stat: 
        path: /home/drake/.zshrc
      register: stat_zshrc
    
    - name: link .zshrc
      file:
        src: /home/drake/dotfiles/zsh/zshrc
        dest: /home/drake/.zshrc
        state: link
      when: (not stat_zshrc.stat.exists) and stat_oh_my_zsh_result.stat.exists  
    
    #check if .zsh_aliases exists:
    - name: checking for .zsh_aliases
      stat: 
        path: /home/drake/.zsh_aliases
      register: stat_zsh_aliases
    
    - name: link .zsh_aliases
      file:
        src: /home/drake/dotfiles/zsh/zsh_aliases
        dest: /home/drake/.zsh_aliases
        state: link
      when: (not stat_zsh_aliases.stat.exists) and stat_oh_my_zsh_result.stat.exists
    
    #check if .zsh-theme exists:
    - name: checking for .zsh-theme
      stat: 
        path: /home/drake/.oh-my-zsh/custom/themes/less-fishy.zsh-theme
      register: stat_zsh_theme
    
    - name: link .zsh-theme
      file:
        src: /home/drake/dotfiles/zsh/less-fishy.zsh-theme
        dest: /home/drake/.oh-my-zsh/custom/themes/less-fishy.zsh-theme
        state: link
      when: (not stat_zsh_theme.stat.exists) and stat_oh_my_zsh_result.stat.exists

    #zsh plugin from git:
    - name: cloning zsh-autosuggestions
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: /home/drake/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      when: stat_oh_my_zsh_result.stat.exists

    #neovim
    - name: checking for init.vim
      stat: 
        path: /home/drake/.config/nvim/init.vim
      register: stat_nvim
    
    - name: link init.vim
      file:
        src: /home/drake/dotfiles/init.vim
        dest: /home/drake/.config/nvim/init.vim
        state: link
      when: not stat_nvim.stat.exists
    
    #set home directory permissions
    - name: set home permissions
      file:
        path: /home/drake
        state: directory
        recurse: yes
        owner: drake
        group: drake
    
