---
- name: configure NFS mount for pihole
  hosts: singularity
  tasks:

    - name: make sure we have the nfs-utils...
      yum:
        name: nfs-common
        state: latest

    #initial NFS check
    - name: create NFS folder
      file:
        path: /mnt/mobius
        state:  directory

    - name: check for NFS folder
      stat:
        path: /mnt/mobius
      register: mobius

    - fail: fail if /mnt/mobius doesn't exist
      when: not mobius.stat.exists

    #mount the NFS share
    - name: Mount the Backup share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Backup
        path: /mnt/mobius/Backup
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: nfs_dir.stat.exists

    #check for directory in the share
    - name: create pihole backup folder
      file:
        path: /mnt/mobius/Backup/pihole
        state:  directory

    - name: check for NFS folder
      stat:
        path: /mnt/mobius/Backup/pihole
      register: pihole

    - fail: fail if /mnt/mobius doesn't exist
      when: not pihole.stat.exists