---
- name: configure NFS mount for pihole
  hosts: singularity
  tasks:

    - name: make sure we have the nfs-utils...
      yum:
        name: nfs-common
        state: latest

    - name: Mount the Backup share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Backup
        path: /mnt/mobius/Backup
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
