---
- hosts: apis_1
  vars:
     helm_chart_url: "https://charts.bitnami.com/bitnami"
  tasks:
    
    # add helm repo
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "{{ helm_chart_url }}"

    # install a chart from said repo
    - name: Install Nginx Chart
      kubernetes.core.helm:
        name: nginx-server
        namespace: dev-test
        chart_ref: bitnami/nginx

    # install chart
    - name: Install Nginx Chart
      kubernetes.core.helm:
        name: nginx-server
        namespace: dev-test
        chart_ref: bitnami/nginx
        # state: absent
        values:
          service:
            loadBalancerIP: 192.168.13.100
        
    # get info about installed chart
    - name: Gather information about nginx-server
      kubernetes.core.helm_info:
        name: nginx-server
        release_namespace: dev-test