---
- hosts:
    - self
  vars:
    host_info_1: "{{ lookup('file', 'vars.json') }}"
    host_info_2: "{{ lookup('file', 'vars2.json') }}"
  tasks:

  - name: "Output all host_info_2 tList as-is"
    debug:
      msg: "{{ host_info_2 }}"

  - name: "Print all hostnames"
    debug:
      msg: "{{ item.hostname }}"
    loop: "{{ host_info_2 }}"

- hosts: apt_cache
  vars:
    host_info_1: "{{ lookup('file', 'vars.json') }}"
  tasks:

  - name: get the specific values for apt-cache.vm
    debug:
      msg:  "hostname: {{ host_info_1.hostnames.apt_cache }}"

  - name: get the specific values for apt-cache.vm
    debug:
      msg:  "password: {{ host_info_1.passwords.apt_cache }}"


- hosts: apt_mirror
  vars:
    host_info_1: "{{ lookup('file', 'vars.json') }}"
  tasks:

  - name: get the specific values for apt-mirror.vm
    debug:
      msg:  "hostname: {{ host_info_1.hostnames.apt_mirror }}"
  
  - name: get the specific values for apt-mirror.vm
    debug:
      msg:  "password: {{ host_info_1.passwords.apt_mirror }}"

