---
- hosts:  all
  tasks:
    - name: test json
      debug:
        msg:  "{{ machines }}"

    - name: test self
      debug:
        msg:  "{{ machines[0].self }}"

    - name: test self
      debug:
        msg:  "{{ machines[0].self.hostname }}"

    - name: test self
      debug:
        msg:  "{{ machines[0].self.password }}"

    - name: test self
      debug:
        msg:  "{{ machines[0].self.LXC }}"