---
- hosts:  all
  tasks:
    - name: test json
      debug:
        msg:  "{{ logins }}"

    - name: test filtering
      debug:
        msg:  "{{ logins[0].login.password }}"
      when: logins[0].name == inventory_hostname
