---
- hosts:  all
  tasks:
    - name: test json
      debug:
        msg:  "{{ machines }}"

    - name: test self
      debug:
        msg:  "{{ machines.self }}"

    - name: test self
      debug:
        msg:  "{{ machines.self.hostname }}"

    - name: test self
      debug:
        msg:  "{{ machines.self.password }}"

    - name: test self
      debug:
        msg:  "{{ machines.self.LXC }}"