---
- name: deploy dotfiles 
  hosts:  
    #TODO: correct reason for these excemptions
    - linux:!origami:!octopi
    - tesseract
  ignore_unreachable: true
  gather_facts: false
  tasks:

    - name:  ping hosts to register if they're up
      ping:
        data: pong
      register: host_up

    #deploy dotfiles repo
    - git:
        repo: 'https://github.com/educatedCaveman/dotfiles.git'
        dest: /home/drake/dotfiles
        force:  yes
      when: host_up.ping is defined
            
    #set home directory permissions
    - name: set home permissions
      file:
        path: /home/drake
        state: directory
        recurse: yes
        owner: drake
        group: drake
      when: host_up.ping is defined
