---
# tasks file for nfs_music_role
- name: Mount the Music NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/Music
    path: /mnt/mobius/Music
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
