- git:
    repo: "git@github.com:educatedCaveman/{{ item }}.git"
    dest: "/home/drake/github/{{ item }}"
  become: true
  become_user:  drake
  ignore_errors: true
  loop:
    - "dotfiles"
    - "fitbit-app-versa4"
    - "fitbit-beta-decay"
    - "fitbit_tinker"
    - "gatus"
    - "hu3bot"
    - "k3s_lab"
    - "klipper"
    - "scripts"