---
# packages
- name: install packages
  import_tasks: packages.yml

# GitHub
- name: clone repos
  import_tasks: github.yml

# ZSH
- name: configure ZSH
  import_tasks: ZSH.yml
 
# NeoVim
- name: configure NeoVim & Vundle
  import_tasks: neovim.yml  

# TMUX
- name: configure TMUX
  import_tasks: tmux.yml

# Discord (configfile)
- name: install Discord config
  import_tasks: discord.yml

# NFS
- name: mount NFS shares
  import_tasks: NFS.yml

# TODO: pull KDE UI and preference configs

# TODO: syncthing/other data

# final installs:
- name: Manual software installs
  debug:
    msg: 
      - "run the following command(s):"
      - "sudo pamac install ultra-flat-icons-blue brother-hll2395dw"
      - "flatpak install flathub tv.plex.PlexDesktop"
      - "flatpak install flathub com.plexamp.Plexamp"
