---
- pacman:
    name: 
      - tmux
      - htop
      - btop
      - yt-dlp
      - neovim
      - discord
      - zsh
      - tmux
      - nfs-utils
      - obsidian
      - bitwarden
      - cuetools
      - fastfetch
      - tree
      - git-crypt
      - kubeseal
      - kustomize
      - k9s
      - shellcheck
      - steam
      - steam-native-runtime
      - fprintd
      # - pantheon-geoclue2-agent
      - syncthing
      - kubectl
    state:  present
