---
- pacman:
    name: 
      - tmux
      - htop
      - btop
      - yt-dlp
      - neovim
      - discord
      - zsh
      - tmux
      - nfs-utils
      - obsidian
      - bitwarden
      - superslicer
      - cuetools
      - fastfetch
      - tree
      - git-crypt
      - kubeseal
    state:  present
