---
- pacman:
    name: 
      - tmux
      - htop
      - btop
      - yt-dlp
      - neovim
      - discord
      - zsh
      - neofetch
      - tmux
      - terminator
      - nfs-utils
      - obsidian
      - bitwarden
      - superslicer
    state:  present
