---
# check for dotfiles
- name: check if the dotfiles are present
  stat:
    path: /home/drake/github/dotfiles
  register: dotfiles

# Tmux installed in packages.yml

# .tmux.conf
- name: checking for .tmux.conf
  stat: 
    path: /home/drake/.tmux.conf
  register: tmux

- name: remove existing .tmux.conf
  file:
    path: /home/drake/.tmux.conf
    state:  absent
  when:
    - dotfiles.stat.exists
    - tmux.stat.islnk is defined
    - tmux.stat.islnk == False

- name: link .tmux.conf
  file:
    src: /home/drake/github/dotfiles/tmux.conf
    dest: /home/drake/.tmux.conf
    state: link

# tmuxinator configs
- name: checking for tmuxp configs
  stat: 
    path: /home/drake/.config/tmuxp
  register: mux

- name: remove existing tmuxp configs
  file:
    path: /home/drake/.tmuxp
    state:  absent
  when:
    - dotfiles.stat.exists
    - mux.stat.islnk is defined
    - mux.stat.islnk == False

- name: link tmuxinator configs
  file:
    src: /home/drake/github/dotfiles/tmuxp_configs
    dest: /home/drake/.tmuxp
    state: link

- name: check for wrong config location
  stat:
    path: /home/drake/.config/tmuxp
  register: bad_config

- name: remove bad config location if it exists
  file:
    path: /home/drake/.config/tmuxp
    state:  absent
