---
# Only deploy once to the manager and worker groups
# if the first is down, that is something that should be looked into anyway
# distributing to the rest is handled by glusterFS
- name: deploy git repo to single DEV Swarm worker
  hosts:  sevastopol
  tasks:

    - name: deploy master branch to the Swarm worker
      git:
        repo: "https://github.com/educatedCaveman/{{ repo }}"
        dest: "/docker/docker-compose/{{ repo }}"
        version:  master
        force:  yes

    - name: diskover repo permissions
      file:
        path:     "/docker/docker-compose/{{ repo }}"
        state:    directory
        recurse:  yes
        owner:    drake
        group:    drake
      when: repo == item
      loop:
        - diskover

    - name: diskover sysctl value
      ansible.posix.sysctl:
        name:       vm.max_map_count
        value:      '262144'
        sysctl_set: yes
        state:      present
        reload:     yes
      when: repo == item
      loop:
        - diskover

- name: deploy docker code to DEV portainer instance
  # only need to deploy once
  hosts: 
    - self
    - dilithium
  tasks:
    
    - name: create the dev_code/docker-compose directory
      file:
        path: "/home/drake/docker_compose_prd/{{ repo }}"
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: "/home/drake/docker_compose_prd/{{ repo }}"
      register: dev_code

    - name: deploy master branch
      git:  
        repo: "https://github.com/educatedCaveman/{{ repo }}"
        dest: "/home/drake/docker_compose_prd/{{ repo }}"
        version:  master
        force:  yes
      when: dev_code.stat.exists

    - name: set permissions on directory
      file:
        path: "/home/drake/docker_compose_prd/{{ repo }}"
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake
