---
# Only deploy once to the manager and worker groups
# if the first is down, that is something that should be looked into anyway
# distributing to the rest is handled by glusterFS
- name: deploy git repo to single Dev Swarm manger/worker
  hosts:  
    - dev_swarm_manager_01
    - dev_swarm_worker_01
  tasks:

    - name: deploy dev_test branch to the Swarm
      git:
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /mnt/gluster/
        version:  dev_test
        force:  yes

- name: deploy docker code to DEV portainer instance
  # only need to deploy once
  hosts: 
    - self
    - dilithium
  tasks:
    
    - name: create the dev_code/docker directory
      file:
        path: /home/drake/dev_code/docker
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/dev_code
      register: dev_code

    - name: deploy dev_test branch
      git:  
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /home/drake/dev_code/docker
        version:  dev_test
        force:  yes
      when: dev_code.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/dev_code
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake
        