---
- name: deploy DEV docker code to NFS mount
  # only need to deploy once
  hosts: 
    - dev_swarm_managers
    - dev_swarm_workers
  tasks:

    # might have to deploy directly instead of to NFS?
    # but that could lead to inconsistency problems
    - name: deploy dev_test branch to dev_swarm_workers
      git:
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /docker
        # dest: /mnt/mobius/docker/dev
        version:  dev_test
        force:  yes

    # - name: set permissions in the directory
    #   file:
    #     path: /mnt/mobius/docker
    #     state:  directory
    #     recurse:  yes
    #     owner:  drake
    #     group:  drake
    # - name: copy docker dev code to NFS
    #   copy:
    #     src:  /var/lib/jenkins/workspace/docker_dev_test/
    #     dest: /mnt/mobius/docker/dev
    #     force:  yes
    #     remote_src: yes

- name: deploy docker code to DEV portainer instance
  # only need to deploy once
  hosts: 
    - self
    - dilithium
  tasks:
    
    - name: create the dev_code/docker directory
      file:
        path: /home/drake/dev_code/docker
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/dev_code
      register: dev_code

    - name: deploy dev_test branch
      git:  
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /home/drake/dev_code/docker
        version:  dev_test
        force:  yes
      when: dev_code.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/dev_code
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake