---
- name: deploy docker code to DEV portainer instance
  # only need to deploy once
  hosts: self
  tasks:

    - name: deploy dev_test branch to dev_swarm_workers
      git:
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /mnt/mobius/docker/dev
        version:  dev_test
        force:  yes

    - name: set permissions in the directory
      file:
        path: /mnt/mobius/docker
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake
    
    - name: create the dev_code/docker directory
      file:
        path: /home/drake/dev_code/docker
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/dev_code
      register: dev_code

    - name: deploy dev_test branch to self
      git:  
        repo: "https://github.com/educatedCaveman/docker-lab"
        dest: /home/drake/dev_code/docker
        version:  dev_test
        force:  yes
      when: dev_code.stat.exists

    - name: set permissions on directory
      file:
        path: /home/drake/dev_code/docker
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake