---
# Only deploy once to the manager and worker groups
# if the first is down, that is something that should be looked into anyway
# distributing to the rest is handled by glusterFS
- name: deploy git repo to Pi
  hosts:  dilithium
  tasks:

    - name: deploy master branch to the Swarm worker
      git:
        repo: "https://github.com/educatedCaveman/{{ repo }}"
        dest: "/docker/docker-compose/{{ repo }}"
        version:  master
        force:  yes

