---
# set permissions for the grafana docker-compose folder
- name: change grafana folder permissions (DEV)
  hosts: lv_426
  tasks:

    - name: change dev folder permissions
      file:
        path: /docker/docker-compose/grafana_apps/grafana
        mode:   '0777'
      when: docker_env == "dev"

# set permissions for the grafana docker-compose folder
- name: change grafana folder permissions (PRD)
  hosts: sevastopol
  tasks:

    - name: change dev folder permissions
      file:
        path: /docker/docker-compose/grafana_apps/grafana
        mode:   '0777'
      when: docker_env == "prd"


