---
# grafana folder permissions documented here:
# https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later

# set permissions for the grafana docker-compose folder
- name: change grafana folder permissions (DEV)
  hosts: lv_426
  tasks:

    - name: change dev folder permissions
      file:
        path: /docker/docker-compose/grafana_apps/grafana
        owner:  "472"
        group:  root    # root is UID=0
        mode:   '0755'
      when: docker_env == "dev"

# set permissions for the grafana docker-compose folder
- name: change grafana folder permissions (PRD)
  hosts: sevastopol
  tasks:

    - name: change dev folder permissions
      file:
        path: /docker/docker-compose/grafana_apps/grafana
        owner:  "472"
        group:  root    # root is UID=0
        mode:   '0755'
      when: docker_env == "prd"
