---
- name: configure k3s control node
  hosts: prd_api_LB
  tasks:
    # make sure all packages are up to date
    - name: update packages
      apt:
        name: "*"
        state: latest

    # make sure all the required packages are installed
    - name: ensure a list of packages installed
      apt:
        name:
          - nginx

    # pull the dotfiles repo for the nginx config
    - name: pull the dotfiles repository
      git:
        repo: "https://github.com/educatedCaveman/dotfiles.git"
        dest: /home/drake/dotfiles
        force: yes

    # make sure the default site is disabled
    - name: make sure the default nginx site is disabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    # handle the load balancer nginx config
    # remove the existing config, if present
    - name:
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    # ensure the link from available to enabled is set
    - name: link the previous config to the enabled sites
      file:
        src: /home/drake/dotfiles/docker_swarm/prd_lb_nginx.conf
        dest: /etc/nginx/nginx.conf
        state: link

    # make sure nginx is running
    - name: ensure nginx is running and enabled
      systemd:
        name: nginx
        state: restarted
        enabled: yes
