- name: Install Dependencies
  community.general.homebrew:
    name:
      - neovim
      - htop
      - tmux
      - neofetch
      - python
      - netdata
      - tmuxinator
    state:  latest
    update_homebrew:  yes
      