---
# tasks file for drake_role
- name: set home permissions
  file:
    path: /Users/drake
    state: directory
    recurse: yes
    owner: drake
    group: drake

#set ssh directory permissions
- name: set ssh permissions
  file:
    path:     /Users/drake/.ssh
    state:    directory
    owner:    drake
    group:    drake
    mode:     '0700'

#set ssh directory permissions
- name: set ssh permissions
  file:
    path:     /Users/drake/.ssh/authorized_keys
    state:    file
    owner:    drake
    group:    drake
    mode:     '0600'
    