---
# tasks file for drake_role
#set ssh directory permissions
- name: set ssh permissions
  file:
    path:     /Users/drake/.ssh
    state:    directory
    owner:    drake
    mode:     '0700'

#set ssh directory permissions
- name: set ssh permissions
  file:
    path:     /Users/drake/.ssh/authorized_keys
    state:    file
    owner:    drake
    mode:     '0600'
    