---
- name: configure galera cluster (DEV)
  hosts: dev_mariadb
  tasks:

    # stop mariadb
    - name: ensure mariadb has been stopped
      systemd:
        name: mariadb
        state: stopped
        enabled: yes

    # pull the dotfiles repo for the galera config
    - name: pull the dotfiles repository
      git:
        repo: "https://github.com/educatedCaveman/dotfiles.git"
        dest: /home/drake/dotfiles
        force: yes

    # remove the existing file
    - name: remove the original galera.cnf files
      file:
        path: /etc/mysql/conf.d/galera.cnf
        state: absent

# there are no existing configs, so we just have to link the custom ones
- name: configure galera on first node
  hosts: dev_db_01
  tasks:

    # copy the new one
    - name: copy the new custom galera.cnf file
      copy:
        src: /home/drake/dotfiles/kubernetes/dev/galera_01.cnf
        dest: /etc/mysql/conf.d/galera.cnf
        remote_src: yes
    
- name: configure galera on first node
  hosts: dev_db_02
  tasks:

    # copy the new one
    - name: copy the new custom galera.cnf file
      copy:
        src: /home/drake/dotfiles/kubernetes/dev/galera_02.cnf
        dest: /etc/mysql/conf.d/galera.cnf
        remote_src: yes
    
- name: configure galera on first node
  hosts: dev_db_03
  tasks:

    # copy the new one
    - name: copy the new custom galera.cnf file
      copy:
        src: /home/drake/dotfiles/kubernetes/dev/galera_03.cnf
        dest: /etc/mysql/conf.d/galera.cnf
        remote_src: yes

- name: initialize the cluster
  hosts: dev_db_01
  tasks:

    # have to run a special command the first time:
    - name: run "galera_new_cluster" on the first node
      shell:
        cmd:  galera_new_cluster

- name: add the remaining nodes to the cluster
  hosts: dev_mariadb
  tasks:

    # make sure mariadb is enabled, and has been restarted
    - name: ensure mariadb is running and enabled
      systemd:
        name: mariadb
        state: restarted
        enabled: yes
