---
- name: mariaDB initial setup
  hosts: dev_mariadb
  tasks:
    # make sure all packages are up to date
    - name: update packages
      apt:
        name: "*"
        state: latest

    # upgrade packages
    - name: upgrade packages
      apt:
        upgrade:  safe

    # make sure all the required packages are installed
    - name: ensure a list of packages installed
      apt:
        name:
          - mariadb-server
          - rsync

    # TODO: manual running of the securing script

    # pull the dotfiles repo for the nginx config
    - name: pull the dotfiles repository
      git:
        repo: "https://github.com/educatedCaveman/dotfiles.git"
        dest: /home/drake/dotfiles
        force: yes

    # stop mariadb
    - name: ensure mariadb has been stopped
      systemd:
        name: mariadb
        state: stopped
        enabled: yes

    # remove the existing file
    - name: remove the original galera.cnf file, if present
      file:
        path: /etc/mysql/conf.d/galera.cnf
        state: absent

    # check if the backup config exists
    - name: check for the backup config file
      stat:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf.backup
      register: mariadb_conf_backup

    # if the backup doesn't exist, create it
    - name: if the backup doesn't exist, create it
      copy:
        src:  /etc/mysql/mariadb.conf.d/50-server.cnf
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf.backup
        remote_src: yes
      when: not(mariadb_conf_backup.stat.exists)

    # make sure mariadb is stopped
    - name: ensure mariadb is running and enabled
      systemd:
        name: mariadb
        state: stopped
        enabled: yes

# copy the new/custom config over
- name: configure galera/mariaDB on the first node
  hosts: dev_db_03
  tasks:

    # copy the new config
    - name: copy the new config
      copy:
        src:  /home/drake/dotfiles/kubernetes/dev/mariadb_01_50-server.cnf
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        remote_src: yes

# copy the new/custom config over
- name: configure galera/mariaDB on the second node
  hosts: dev_db_03
  tasks:

    # copy the new config
    - name: copy the new config
      copy:
        src:  /home/drake/dotfiles/kubernetes/dev/mariadb_02_50-server.cnf
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        remote_src: yes
        
# copy the new/custom config over
- name: configure galera/mariaDB on the third node
  hosts: dev_db_03
  tasks:

    # copy the new config
    - name: copy the new config
      copy:
        src:  /home/drake/dotfiles/kubernetes/dev/mariadb_03_50-server.cnf
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        remote_src: yes

#only need to run this the first time
# - name: initialize the cluster
#   hosts: dev_db_01
#   tasks:

#     # have to run a special command the first time:
#     - name: run "galera_new_cluster" on the first node
#       shell:
#         cmd:  galera_new_cluster

- name: add the remaining nodes to the cluster
  hosts: dev_mariadb
  tasks:

    # make sure mariadb is enabled, and has been restarted
    - name: ensure mariadb is running and enabled
      systemd:
        name: mariadb
        state: restarted
        enabled: yes
