---
- name: configure k3s control node
  hosts: dev_mariadb
  tasks:

    # stop mariadb
    - name: ensure mariadb has been stopped
      systemd:
        name: mariadb
        state: stopped
        enabled: yes

    # pull the dotfiles repo for the galera config
    - name: pull the dotfiles repository
      git:
        repo: "https://github.com/educatedCaveman/dotfiles.git"
        dest: /home/drake/dotfiles
        force: yes
    
- name: configure galera on first node
  hosts: dev_db_01
  tasks:

    # copy the default config, if the backup doesn't exist
    - name: check if backup config exists
      stat:
        path: /etc/mysql/conf.d/galera.cnf.backup
      register: backup_galera_conf

    - name: copy the default config, if the backup doesn't exist
      copy:
        src: /etc/mysql/conf.d/galera.cnf
        dest: /etc/mysql/conf.d/galera.cnf.backup
        remote_src: yes
      when: not backup_galera_conf.stat.exists

    # remove the original
    - name: remove the original config file
      file:
        path: /etc/mysql/conf.d/galera.cnf
        state: absent

    # link the custom one
    - name: link the new custom config file
      file:
        src: /home/drake/dotfiles/kubernetes/dev/galera_01.cnf
        dest: /etc/mysql/conf.d/galera.cnf
        state:  link
    
- name: configure galera on first node
  hosts: dev_db_02
  tasks:

    # copy the default config, if the backup doesn't exist
    - name: check if backup config exists
      stat:
        path: /etc/mysql/conf.d/galera.cnf.backup
      register: backup_galera_conf

    - name: copy the default config, if the backup doesn't exist
      copy:
        src: /etc/mysql/conf.d/galera.cnf
        dest: /etc/mysql/conf.d/galera.cnf.backup
        remote_src: yes
      when: not backup_galera_conf.stat.exists

    # remove the original
    - name: remove the original config file
      file:
        path: /etc/mysql/conf.d/galera.cnf
        state: absent

    # link the custom one
    - name: link the new custom config file
      file:
        src: /home/drake/dotfiles/kubernetes/dev/galera_02.cnf
        dest: /etc/mysql/conf.d/galera.cnf
        state:  link
    
- name: configure galera on first node
  hosts: dev_db_03
  tasks:

    # copy the default config, if the backup doesn't exist
    - name: check if backup config exists
      stat:
        path: /etc/mysql/conf.d/galera.cnf.backup
      register: backup_galera_conf

    - name: copy the default config, if the backup doesn't exist
      copy:
        src: /etc/mysql/conf.d/galera.cnf
        dest: /etc/mysql/conf.d/galera.cnf.backup
        remote_src: yes
      when: not backup_galera_conf.stat.exists

    # remove the original
    - name: remove the original config file
      file:
        path: /etc/mysql/conf.d/galera.cnf
        state: absent

    # link the custom one
    - name: link the new custom config file
      file:
        src: /home/drake/dotfiles/kubernetes/dev/galera_03.cnf
        dest: /etc/mysql/conf.d/galera.cnf
        state:  link

- name: initialize the cluster
  hosts: dev_db_01
  tasks:

    # have to run a special command the first time:
    - name: run "galera_new_cluster" on the first node
      shell:
        cmd:  galera_new_cluster

- name: add the remaining nodes to the cluster
  hosts: 
    - dev_db_02
    - dev_db_03
  tasks:

    # make sure mariadb is enabled, and has been restarted
    - name: ensure mariadb is running and enabled
      systemd:
        name: mariadb
        state: restarted
        enabled: yes
