# installing the correct telegraf config

# check for dotfiles
- name: check if the dotfiles are present
  stat:
    path: /home/drake/dotfiles
  register: dotfiles

# if dotfiles are present, overwrite the existing config
- name: install telegraf.conf
  copy:
    src:    "/home/drake/dotfiles/telegraf/{{ telegraf_config }}"
    dest:   /etc/telegraf/telegraf.conf
    force:  yes
  when: 
    - dotfiles.stat.exists
