- name: install influxDB/telegraf prerequisites
  apt:
    name:
      - gpg
    state:  present

# add the key
- name: add the APT key for influxDB and related things
  apt_key:
    url:    https://repos.influxdata.com/influxdb.key
    state:  present

# add the repo
- name: add the influxDB repository
  apt_repository:
    repo:   "deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable"
    state:  present
    update_cache: yes

# install Telegraf
- name: install telegraf 
  apt:
    name:   telegraf
    state:  present
    