---
- name: create the dotfiles/ directory
  file:
    path: /home/drake/dotfiles
    state:  directory
    recurse:  yes

- name: make sure directory exists
  stat:
    path: /home/drake/dotfiles
  register: dotfiles_dir

- name: deploy dotfiles repo
  - git:
      repo: 'https://github.com/educatedCaveman/dotfiles.git'
      dest: /home/drake/dotfiles
      force:  yes
    when: dotfiles_dir.stat.exists