---
# tasks file for nfs_backup_role
- name: create the mount directory
  file:
    path:     /mnt/mobius/Backup
    state:    directory
    recurse:  yes

- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/Backup
  register: backup_dir

- name: Mount the Backup NFS share if the mount path exists
  mount:
    src:    192.168.11.2:/mnt/storage_node/Backup
    path:   /mnt/mobius/Backup
    fstype: nfs 
    opts:   rw,nolock,tcp
    state:  mounted
  when: backup_dir.stat.exists
