---
# start openvpn
- name: start openVPN
  systemd:
    name:     openvpn-client@amsterdam_2.service
    state:    started
    enabled:  yes

- name: wait a few seconds for the connection to be established
  wait_for:
    timeout:  5

# start qbittorrent-nox
- name: start qibttorrent
  systemd:
    name:     qbittorrent-nox.service
    state:    started
    enabled:  yes

