---
# tasks file for apt_client_role

# /etc/default/apt-proxy-checker
- name: install apt-proxy config
  copy:
    src:  apt-proxy-checker
    dest: /etc/default/apt-proxy-checker

# /usr/local/bin/apt-proxy-checker.sh 
- name: install apt-proxy-checker.sh
  copy:
    src:  apt-proxy-checker.sh
    dest: /usr/local/bin/apt-proxy-checker.sh 
    mode: 0755

# /etc/apt/apt.conf.d/10apt-cache
- name: install apt-cache client config
  copy:
    src:  11-apt-cache
    dest: /etc/apt/apt.conf.d/10-apt-cache

