---
# tasks file for client_ssh_keys

# root keys:
- name: install keys for root
  ansible.posix.authorized_key:
    user:   root
    state:  present
    key:    '{{ item }}'
  with_file:
    - /home/drake/.ssh/id_ed25519.pub
    - /home/drake/.ssh/jenkins_id_ed25519.pub
    - /home/drake/.ssh/dilithium_id_ed25519.pub
    - /home/drake/.ssh/carbon_id_ed25519.pub
    - /home/drake/.ssh/theseus_id_ed25519.pub

# drake keys:
- name: install keys for drake
  ansible.posix.authorized_key:
    user:   drake
    state:  present
    key:    '{{ item }}'
  with_file:
    - /home/drake/.ssh/id_ed25519.pub
    - /home/drake/.ssh/jenkins_id_ed25519.pub
    - /home/drake/.ssh/dilithium_id_ed25519.pub
    - /home/drake/.ssh/carbon_id_ed25519.pub
    - /home/drake/.ssh/theseus_id_ed25519.pub

# restart ssh service
- name: restart sshd
  systemd:
    name:     sshd.service
    state:    restarted
    enabled:  yes