---
# tasks file for client_ssh_keys

# # copy local authorized_keys to /root/.ssh
# - name: check for root's ssh folder
#   stat:
#     path: /root/.ssh/
#   register: root_ssh

# - name: install local authorized_keys to root
#   copy:
#     src:    /home/drake/.ssh/authorized_keys
#     dest:   /root/.ssh/authorized_keys
#     owner:  root
#     group:  root
#     mode:   '0600'
#     force:  yes
#   when: root_ssh.stat.exists

# # copy local authorized_keys to /home/drake/.ssh
# - name: check for drake's ssh folder
#   stat:
#     path: /home/drake/.ssh/
#   register: drake_ssh

# - name: install local authorized_keys to drake
#   copy:
#     src:    /home/drake/.ssh/authorized_keys
#     dest:   /home/drake/.ssh/authorized_keys
#     owner:  drake
#     group:  drake
#     mode:   '0600'
#     force:  yes
#   when: root_ssh.stat.exists


# root keys:
- name: install keys for root
  authorized_keys:
    user:   root
    state:  present
    key:    '{{ item }}'
  with_file:
    - /home/drake/.ssh/id_ed25519.pub
    - /home/drake/.ssh/jenkins_id_ed25519.pub
    - /home/drake/.ssh/dilithium_id_ed25519.pub
    # - /home/drake/.ssh/carbon_id_ed25519.pub
    # - /home/drake/.ssh/theseus_id_ed25519.pub

# drake keys:
- name: install keys for drake
  authorized_keys:
    user:   drake
    state:  present
    key:    '{{ item }}'
  with_file:
    - /home/drake/.ssh/id_ed25519.pub
    - /home/drake/.ssh/jenkins_id_ed25519.pub
    - /home/drake/.ssh/dilithium_id_ed25519.pub
    - /home/drake/.ssh/carbon_id_ed25519.pub
    - /home/drake/.ssh/theseus_id_ed25519.pub



# restart ssh service
- name: restart sshd
  systemd:
    name:     sshd.service
    state:    restarted
    enabled:  yes