---
# tasks file for git_scripts_role
- name: Deploy the scripts git repository
  git:
    repo: https://github.com/educatedCaveman/scripts
    dest: /home/drake/scripts
    version:  master

# copy over .zsh_secrets
- name: copy .zsh_secrets
  copy:
    src:  /home/drake/.zsh_secrets
    dest: /home/drake/.zsh_secrets
    owner:  drake
    group:  drake
    mode: '0644'
    