---
# tasks file for drake_role
- name: set home permissions
  file:
    path: /home/drake
    state: directory
    recurse: yes
    owner: drake
    group: drake

#set ssh directory permissions
- name: set ssh folder permissions
  file:
    path:     /home/drake/.ssh
    state:    directory
    owner:    drake
    group:    drake
    mode:     '0744'

#set ssh directory permissions
- name: set authorized_keys permissions
  file:
    path:     /home/drake/.ssh/authorized_keys
    state:    file
    owner:    drake
    group:    drake
    mode:     '0644'
    