---
- name: configure Ansible/Jenkins
  hosts:  self
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role    # needed for things outside this playbook
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - nfs_backup_role
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

  - name: Install main packages
    apt:
      name:
        - ansible
        # - ansible-galaxy
        - gpg
        - default-jre
        - default-jdk
        - unzip
        - jq          # for bitwarden script
      state:  latest

  # Jenkins config
  - name: add Jenkins Key
    apt_key:
      url:  https://pkg.jenkins.io/debian-stable/jenkins.io.key

  - name: add Jenkins repo
    apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      update_cache: yes
      state: present
      filename: jenkins.list

  - name: Install Jenkins
    apt:
      name:
        - jenkins
      state:  latest

  - name: enable and restart jenkins
    systemd:
      name: jenkins
      state:  started
      enabled:  yes

  # initial admin password:
  - name: Initial admin password
    debug:
      msg: 
        - "to get the initial admin password, run the following:"
        - cat /var/lib/jenkins/secrets/initialAdminPassword

  - name: Jenkins setup
    debug:
      msg:  the ability to restore th jenkins from backup config would go here?

  # Semaphore (Web UI for Ansible)
  # https://github.com/ansible-semaphore/semaphore/releases/download/v2.7.0/semaphore_2.7.0_linux_amd64.deb

  # bitwarden config
  - name: check for bitwarden
    stat:
      path: /usr/local/sbin/bw
    register: bw_installed

  - name: install bitwarden
    get_url:
      url: https://vault.bitwarden.com/download/?app=cli&platform=linux
      dest: /tmp/bw.zip
    when: not bw_installed.stat.exists

  - name: check that downloaded file exists
    stat:
      path: /tmp/bw.zip
    register: bw_zip

  - name: unzip bitwarden
    unarchive:
      src:  /tmp/bw.zip
      dest: /usr/local/sbin/
      remote_src: yes
      mode: a+x
      