---

# goals:
#   install configs
#   pull git repos
# install some key packages
# NFS mounts


# run cmd:
# ansible-playbook hosts/carbon.yml -i hosts.ini --key-file "/home/drake/.ssh/carbon_id_ed25519"

- name: Install Useful/QoL Packages
  hosts:  carbon_local
  tasks:

  - pacman:
      name: 
        - tmux
        - htop
        - btop
        - yt-dlp
        - neovim
        - discord
        - zsh
        - neofetch
        - tmux
        - terminator
      state:  present

  # TODO: AUR packages:
  # ultra-flat-icons-blue

# # TODO: can't get this to work right now
# - name: Clone Git Repositories
#   hosts:  carbon_local
#   tasks:

#   - name: Pull Git Repositories
#     git:
#       repo: 'git@github.com:educatedCaveman/dotfiles.git'
#       dest: /home/drake/github/dotfiles


# ZSH
- name: Configure ZSH
  hosts:  carbon_local
  tasks:
  
  # check for dotfiles
  - name: check if the dotfiles are present
    stat:
      path: /home/drake/github/dotfiles
    register: dotfiles

  # ZSH installed above

  # change shell
  - name: change to ZSH
    user:
      name: drake
      shell: /usr/bin/zsh
    when: dotfiles.stat.exists

  # clone the repo 
  - name: cloning  oh-my-zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: /home/drake/.oh-my-zsh
    when: dotfiles.stat.exists

  # check for .oh-my-zsh
  - name: check if .oh-my-zsh exists
    stat:
      path: /home/drake/.oh-my-zsh
    register: oh_my_zsh

  # check if .zshrc exists:
  - name: checking for .zshrc
    stat: 
      path: /home/drake/.zshrc
    register: zshrc

  - name: remove existing config
    file:
      dest: /home/drake/.zshrc
      state:  absent
    when:
      - zshrc.stat.exists
      - zshrc.stat.islnk == false

  - name: link .zshrc
    file:
      src: /home/drake/github/dotfiles/zsh/zshrc
      dest: /home/drake/.zshrc
      state: link
    when: 
      - not zshrc.stat.exists
      - oh_my_zsh.stat.exists
      - dotfiles.stat.exists

  # check if .zsh_aliases exists:
  - name: checking for .zsh_aliases
    stat: 
      path: /home/drake/.zsh_aliases
    register: zsh_aliases

  - name: link .zsh_aliases
    file:
      src: /home/drake/github/dotfiles/zsh/zsh_aliases
      dest: /home/drake/.zsh_aliases
      state: link
    when: 
      - not zsh_aliases.stat.exists
      - oh_my_zsh.stat.exists
      - dotfiles.stat.exists

  # check if .zsh-theme exists:
  - name: checking for .zsh-theme
    stat: 
      path: /home/drake/.oh-my-zsh/custom/themes/less-fishy.zsh-theme
    register: zsh_theme

  - name: link .zsh-theme
    file:
      src: /home/drake/github/dotfiles/zsh/less-fishy.zsh-theme
      dest: /home/drake/.oh-my-zsh/custom/themes/less-fishy.zsh-theme
      state: link
    when: 
      - not zsh_theme.stat.exists
      - oh_my_zsh.stat.exists
      - dotfiles.stat.exists

  # zsh plugin from git:
  - name: cloning zsh-autosuggestions
    git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: /home/drake/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    when: oh_my_zsh.stat.exists


# NeoVim
- name: Configure NeoVim
  hosts:  carbon_local
  tasks:

  # check that dotfiles are present
  - name: checking for dotfiles
    stat:
      path: /home/drake/github/dotfiles
    register: dotfiles

  # Neovim installed above

  # create Vundle directory, which also creates the nvim directory
  - name: create NeoVim and Vundle directories
    file:
      path: /home/drake/.config/nvim/bundle
      state: directory
      recurse: yes
    when: dotfiles.stat.exists

  # Vundle
  - name: verify Vundle directory exists
    stat:
      path: /home/drake/.config/nvim/bundle
    register: bundle

  - name: cloning Vundle
    git:
      repo: 'https://github.com/VundleVim/Vundle.vim.git'
      dest: /home/drake/.config/nvim/bundle/Vundle.vim
    when: bundle.stat.exists

  #neovim
  - name: checking for init.vim
    stat: 
      path: /home/drake/.config/nvim/init.vim
    register: nvim

  # link config file to proper config location
  - name: link init.vim
    file:
      src: /home/drake/github/dotfiles/init.vim
      dest: /home/drake/.config/nvim/init.vim
      state: link
    when: 
      - not nvim.stat.exists
      - dotfiles.stat.exists
  

# TMUX
- name: Configure TMUX
  hosts:  carbon_local
  tasks:

  # check for dotfiles
  - name: check if the dotfiles are present
    stat:
      path: /home/drake/github/dotfiles
    register: dotfiles

  # Tmux installed above

  # .tmux.conf
  - name: checking for .tmux.conf
    stat: 
      path: /home/drake/.tmux.conf
    register: tmux

  - name: remove existing .tmux.conf
    file:
      path: /home/drake/.tmux.conf
      state:  absent
    when:
      - dotfiles.stat.exists
      - tmux.stat.islnk is defined
      - tmux.stat.islnk == False

  - name: link .tmux.conf
    file:
      src: /home/drake/github/dotfiles/tmux.conf
      dest: /home/drake/.tmux.conf
      state: link

  # tmuxinator configs
  - name: checking for tmuxp configs
    stat: 
      path: /home/drake/.config/tmuxp
    register: mux

  - name: remove existing tmuxp configs
    file:
      path: /home/drake/.tmuxp
      state:  absent
    when:
      - dotfiles.stat.exists
      - mux.stat.islnk is defined
      - mux.stat.islnk == False

  - name: link tmuxinator configs
    file:
      src: /home/drake/github/dotfiles/tmuxp_configs
      dest: /home/drake/.tmuxp
      state: link

  - name: check for wrong config location
    stat:
      path: /home/drake/.config/tmuxp
    register: bad_config

  - name: remove bad config location if it exists
    file:
      path: /home/drake/.config/tmuxp
      state:  absent


# Discord (configfile)
- name: Discord Config
  hosts: carbon_local
  tasks:

  # check for dotfiles
  - name: check if the dotfiles are present
    stat:
      path: /home/drake/github/dotfiles
    register: dotfiles

  # existing config file
  - name: checking for exsting settings.json
    stat: 
      path: /home/drake/.config/discord/settings.json
    register: discord_settings

  # remove existing file
  - name: remove existing settings.json
    file:
      path: /home/drake/.config/discord/settings.json
      state:  absent
    when:
      - discord_settings.stat.exists
      - discord_settings.stat.islnk == False

  # link config
  - name: install special config
    file:
      src:    /home/drake/github/dotfiles/discord_settings.json
      dest:   /home/drake/.config/discord/settings.json
      state:  link



# lastly, fix home directory permissions
- name: Home Permissions
  hosts: carbon_local
  tasks:

  - name: fix home dir permissions
    file:
      path:     /home/drake/
      recurse:  true
      owner:    drake
      group:    drake