- name: configure dilithium (spare pi)
  hosts:  dilithium
  roles:
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_ansible_role    # deploy the ansible repo
    - git_scripts_role    # deploy the scripts repo
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
  tasks:

    # install ansible
    - name: install ansible
      apt:
        name:
          - ansible
        state:  latest

    # inventory file
    - name: check existing hosts.ini file
      stat:
        path: /etc/ansible/hosts.ini
      register: hosts

    - name: remove existing host file if it isn't a link
      file:
        path: /etc/ansible/hosts.ini
        state:  absent
      when: hosts.stat.islnk is defined and hosts.stat.islnk == False

    - name: link new hosts file
      file:
        src:  /home/drake/ansible/hosts.ini
        dest: /etc/ansible/hosts
        state:  link

    # config file
    - name: check existing ansible.cfg file
      stat:
        path: /etc/ansible/ansible.cfg
      register: config

    - name: remove existing ansible.cfg file if it isn't a link
      file:
        path: /etc/ansible/ansible.cfg
        state:  absent
      when: config.stat.islnk is defined and config.stat.islnk == False

    - name: link new ansible.cfg file
      file:
        src:  /home/drake/ansible/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        state:  link

    # roles
    - name: check existing ansible.cfg file
      stat:
        path: /etc/ansible/ansible.cfg
      register: roles

    - name: remove existing roles folder/link
      file:
        path: /etc/ansible/roles
        state:  absent
      when: roles.stat.islnk is defined and roles.stat.islnk == False

    - name: link new roles folder
      file:
        src:  /home/drake/ansible/roles
        dest: /etc/ansible/roles
        state:  link

    # jenkins repo
    - debug:
        msg:  "deployment of jenkins repo is handled by jenkins"


