---
- name: configure Forgejo
  hosts:  forgejo
  roles:
    - LXC_role
    - git_config_role
    - git_dotfiles_role
    - git_scripts_role
    - linux_role
    - client_ssh_keys
    - drake_role
    - nfs_base_role
    - nfs_backup_role
  vars:
    # vars to indicate maintenance mode, upgrade, or install?
    forgejo_version:  "15.0.7"
  tasks:

  - name: Install main packages
    apt:
      name:
        - ansible
        # - git       # forgejo requirement
        # - git-lfs   # forgejo requirement
        - curl
        - apt-transport-https
      state:  latest

  # general prep
  - name: Create the git group
    ansible.builtin.group:
      name: git

  - name: Create a git user
    ansible.builtin.user:
      name:     git
      groups:   git
      system:   true
      shell:    /bin/bash
      home:     /home/git
      comment:  'Git Version Control'
      password: '!'                   # disabled password

  - name: Add drake to the git group
    ansible.builtin.user:
      name:   drake
      groups: git
      append: true

  # create folders
  - name: Create /var/lib/forgejo
    ansible.builtin.file:
      path:   /var/lib/forgejo
      state:  directory
      owner:  git
      group:  git
      mode:   '0750'

  - name: Create /etc/forgejo
    ansible.builtin.file:
      path:   /var/lib/forgejo
      state:  directory
      owner:  root  # not a typo
      group:  git
      mode:   '0770'

  # this has been built based on these instructions:
  # https://forgejo.org/docs/latest/admin/installation/binary/

  # download the binary to /usr/local/bin/forgejo, but only if its not already installed
  # https://codeberg.org/forgejo/forgejo/releases/download/v15.0.7/forgejo-15.0.7-linux-amd64
  - name: Check for existing installation
    ansible.builtin.stat:
      path: /usr/local/bin/forgejo
    register: forgejo_bin

  - name: Download the binary
    ansible.builtin.get_url:
      url: "https://codeberg.org/forgejo/forgejo/releases/download/v{{ forgejo_version }}/forgejo-{{ forgejo_version }}-linux-amd64"
      dest: /usr/local/bin/forgejo
      mode: '0750'
    when: not forgejo_bin.stat.exists

  # using sqlite, so no DB setup needed, but this is where it would go

  # start and enable the service
  - name: Download the SystemD service file
    ansible.builtin.get_url:
      url:  https://codeberg.org/forgejo/forgejo/raw/branch/forgejo/contrib/systemd/forgejo.service
      dest: /etc/systemd/system/forgejo.service

  - name: Start and Enable the service
    ansible.builtin.systemd_service:
      name:           forgejo.service
      enabled:        true
      state:          started
      daemon_reload:  true




