- name: configure Graylog
  hosts:  graylog
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

  # this is based off of the following guide:
  # https://docs.graylog.org/en/4.0/pages/installation/os/ubuntu.html

  # prerequisites
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https 
        - openjdk-8-jre-headless 
        - uuid-runtime 
        - pwgen
      state:  present

  # check for dotfiles
  - name: check if the dotfiles are present
    stat:
      path: /home/drake/dotfiles
    register: dotfiles

  # mongoDB
  - name: add MongoDB Key
    apt_key:
      url:  https://www.mongodb.org/static/pgp/server-4.4.asc

  - name: add MongoDB repo
    apt_repository:
      repo: deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
      update_cache: yes
      state: present
      filename: mongodb-org-4.4.list

  - name: Install MongoDB
    apt:
      name:
        - mongodb-org
      state:  latest

  - name: enable and restart MongoDB
    systemd:
      name: mongod
      state:  started
      enabled:  yes

  # elasticsearch
  - name: add Elasticsearch Key
    apt_key:
      url:  https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: add Elasticsearch repo
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      update_cache: yes
      state: present
      filename: elastic-7.x.list
  
  # modify config
  - name: check for existing elasticsearch.yml
    stat:
      path: /etc/elasticsearch/elasticsearch.yml
    register: es_conf

  - name: check for existing elasticsearch.yml.bkup
    stat:
      path: /etc/elasticsearch/elasticsearch.yml.bkup
    register: es_conf_bkup

  - name: backup elasticsearch.yml if the backup doesn't exist
    copy:
      src:  /etc/elasticsearch/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml.bkup
      remote_src: yes
    when: not es_conf_bkup.stat.exists

  - name: remove the existing elasticsearch.yml
    file:
      path: /etc/elasticsearch/elasticsearch.yml
      state:  absent
    when: 
      - dotfiles.stat.exists
      - es_conf.stat.islnk is defined
      - es_conf.stat.islnk == False

  - name: link elasticsearch.yml
    file:
      src:  /home/drake/dotfiles/graylog/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      state:  link
    when: 
      - dotfiles.stat.exists
      - es_conf.stat.islnk is defined
      - es_conf.stat.islnk == False

  - name: Install Elasticsearch
    apt:
      name:
        - elasticsearch
      state:  latest

  - name: enable and restart Elasticsearch
    systemd:
      name: elasticsearch
      state:  started
      enabled:  yes

  # graylog
  - name: fetch graylog package
    apt:
      deb:  https://packages.graylog2.org/repo/packages/graylog-4.0-repository_latest.deb

  - name: install graylog and related packages
    apt:
      name:
        - graylog-server 
        - graylog-enterprise-plugins 
        - graylog-integrations-plugins 
        - graylog-enterprise-integrations-plugins

  # config:  /etc/graylog/server/server.conf
  - name: check for existing graylog server.conf
    stat:
      path: /etc/graylog/server/server.conf
    register: server_conf

  - name: check for existing graylog server.conf.bkup
    stat:
      path: /etc/graylog/server/server.conf.bkup
    register: server_conf_bkup

  - name: backup graylog server.conf if the backup doesn't exist
    copy:
      src:  /etc/graylog/server/server.conf
      dest: /etc/graylog/server/server.conf.bkup
      remote_src: yes
    when: not server_conf_bkup.stat.exists

  - name: remove the existing graylog server.conf
    file:
      path: /etc/graylog/server/server.conf
      state:  absent
    when: 
      - dotfiles.stat.exists
      - server_conf.stat.islnk is defined
      - server_conf.stat.islnk == False

  - name: link graylog server.conf
    file:
      src:  /home/drake/dotfiles/graylog/server.conf
      dest: /etc/graylog/server/server.conf
      state:  link
    when: 
      - dotfiles.stat.exists
      - server_conf.stat.islnk is defined
      - server_conf.stat.islnk == False

  # start graylog service

