- name: configure Graylog
  hosts:  graylog
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

  # this is based off of the following guide:
  # https://docs.graylog.org/en/4.0/pages/installation/os/ubuntu.html

  # prerequisites
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https 
        - openjdk-8-jre-headless 
        - uuid-runtime 
        - pwgen
      state:  present

  # mongoDB
  - name: add MongoDB Key
    apt_key:
      url:  https://www.mongodb.org/static/pgp/server-4.4.asc

  - name: add MongoDB repo
    apt_repository:
      repo: deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
      update_cache: yes
      state: present
      filename: mongodb-org-4.4.list

  - name: Install MongoDB
    apt:
      name:
        - mongodb-org
      state:  latest

  - name: enable and restart MongoDB
    systemd:
      name: mongod
      state:  started
      enabled:  yes

  # elasticsearch
  # - modify config

  - name: add Elasticsearch Key
    apt_key:
      url:  https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: add Elasticsearch repo
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      update_cache: yes
      state: present
      filename: elastic-7.x.list

  - name: Install Elasticsearch
    apt:
      name:
        - elasticsearch
      state:  latest

  # - name: enable and restart Elasticsearch
  #   systemd:
  #     name: elasticsearch
  #     state:  started
  #     enabled:  yes


  # graylog


  # config




