- name: configure Graylog
  hosts:  graylog
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:


