- name: configure influxDB
  hosts:  influxDB
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role
    - nfs_backup_role
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

  # install influxdb
  - name: install influxDB and telegraf
    apt:
      name:   
        - influxdb
        # - telegraf
      state:  present

  # start and enable with systemd
  - name: enable influxDB
    systemd:
      name:     influxdb
      state:    restarted
      enabled:  yes
