---
- name: configure Jellyfin
  hosts:  jellyfin
  roles:
    - linux_role
    - nfs_base_role
    - nfs_backup_role
    - nfs_video_role
  tasks:

  # - name: install Jellyfin pre-requisites
  #   apt:
  #     name:
  #     - apt-transport-https
  #     state:  latest

  # - name: add Jellyfin apt key
  #   apt_key:
  #     url:    https://repo.jellyfin.org/jellyfin_team.gpg.key
  #     state:  present

  # - name: add Jellyfin repo
  #   apt_repository:
  #     repo:     "deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main"
  #     state:    present
  #     filename: /etc/apt/sources.list.d/jellyfin.list

  # - name: update apt cache
  #   apt:
  #     name: jellyfin
  #     update_cache: yes

  # curl -s https://repo.jellyfin.org/install-debuntu.sh -O && \
  # curl -s https://repo.jellyfin.org/install-debuntu.sh.sha256sum -O && \
  # sha256sum -c install-debuntu.sh.sha256sum

  - name: Check for presence of installation script
    stat:
      path: /home/drake/install-debuntu.sh
    register: jf_installer

  - name: Jellyfin's installation script
    ansible.builtin.get_url:
      url:  https://repo.jellyfin.org/install-debuntu.sh
      dest: /home/drake/
    when: not jf_installer.stat.exists

  # Manual steps
  - name: manual installation
    ansible.builtin.debug:
      msg:
      - "Install Jellyfin by running this command:"
      - "sudo bash install-debuntu.sh"