# configure Kubernetes cluster using k3s
- name: configure K3S Cluster
  hosts:
    - k3s
  roles: 
    - VM_role
    - git_config_role
    - git_dotfiles_role
    - linux_role
    - drake_role
    - docker_role
  tasks:

    # longhorn requires the nfs-common and open-iscsi packages
    - name: longhorn requirements
      ansible.builtin.apt:
        name:
          - nfs-common
          - open-iscsi
        state: latest
        update_cache:  yes

    # ensuring open-iscsi is started and enabled (for longhorn)
    - name: start open-iscsi
      ansible.builtin.systemd:
        name:     open-iscsi
        enabled:  true
        state:    started

# - name: Configure Manager Nodes
#   hosts:
#     - k3s_managers
#   roles:
#   tasks:

# - name: Configure Worker Nodes
#   hosts:
#     - k3s_workers
#   roles:
#   tasks:

# - name: Configure Data Nodes
#   hosts:
#     - k3s_data
#   roles:
#   tasks:

