- name: configure lil debbie
  hosts:  lil_debbie
  roles:
    - git_dotfiles_role   # deploy the dotfiles repo
    - linux_role          # base linux configs
    - client_ssh_keys
    - drake_role          # drake home directory permissions
    # - rpi_role
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

    
