- name: configure Minio
  hosts:  minio
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

  # most of this is based on the following guide
  # https://www.digitalocean.com/community/tutorials/how-to-set-up-an-object-storage-server-using-minio-on-ubuntu-18-04

  # create minio group
  - name: create the minio-user group
    group:
      name:   minio-user
      state:  present

  # create minio user
  - name: create minio user
    user:
      name:   minio-user
      group:  minio-user
      system: yes
      state:  present
      shell:  /sbin/nologin

  ###################################################################
  # DIRECTORIES                                                     #
  ###################################################################

  # NFS mount, for data storage
  - name: check for the Minio directory before mounting
    stat: 
      path: /mnt/mobius/minio
    register: s3_dir
    
  # this directory replaces /usr/local/share/minio in the guide above
  - name: create the mount directory
    file:
      path:   /mnt/mobius/minio
      owner:  minio-user
      group:  minio-user
      state:  directory
      recurse:  yes
    when: not s3_dir.stat.exists

  - name: Mount the Minio NFS share if the mount path exists
    mount:
      src:    192.168.11.2:/mnt/storage_node/minio
      path:   /mnt/mobius/minio
      fstype: nfs 
      opts:   rw,nolock,tcp
      state:  mounted

  # create /etc/minio and set permissions
  - name: create /etc/minio folder and set permissions
    file:
      path: /etc/minio
      state:  directory

  # create /usr/local/bin/minio and set permissions
  # - name: create /usr/local/bin/minio folder and set permissions
  #   file:
  #     path: /usr/local/bin/minio
  #     owner:  minio-user
  #     group:  minio-user
  #     state:  directory

  # create /usr/local/share/minio and set permissions
  # - name: create /usr/local/share/minio folder and set permissions
  #   file:
  #     path: /usr/local/share/minio
  #     owner:  minio-user
  #     group:  minio-user
  #     state:  directory

  # get and install Minio  
  - name: retrieve Minio
    get_url:
      src:  'https://dl.min.io/server/minio/release/linux-amd64/minio'
      dest: /tmp/minio

  - name: install Minio
    copy:
      src:  /tmp/minio
      dest: /usr/local/bin/minio
      mode: 'a+x'
      remote_src: yes

  # install /etc/default/minio
  # contains private keys, so should be handled carefully
  # for now, just have it in the file, and only have it accessible internally.
  # if I want to allow it externally, i would need to come up with a better way, after changing it
  - name: install minio env file
    file:
      src:  /home/drake/dotfiles/minio/minio.conf
      dest: /etc/default/minio
      state:  link

  # download, edit, and install service file
  - name: install minio service file
    copy:
      src:  /home/drake/dotfiles/minio/minio.service
      dest: /etc/systemd/system/minio.service
      remote_src: yes

  # disabled so i can verify things
  # # start and enable daemon
  # - name: enable and restart minio
  #   systemd:
  #     name:   minio
  #     state:  restarted
  #     enabled:  yes

