- name: configure octopi
  hosts:  octopi
  roles:
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_ansible_role    # deploy the ansible repo
    - git_scripts_role    # deploy the scripts repo
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

    - name: deploy the franken-printer configs
      git:
        repo:     https://github.com/educatedCaveman/klipper.git
        dest:     /home/drake/franken-printer
        version:  master
        force:    yes

    - name: link the main printer config
      file:
        src:    /home/drake/franken-printer/franken-printer.cfg
        dest:   /home/pi/printer.cfg
        state:  link
        owner:  pi
        group:  drake
        mode:   '0664'

    - name: link the configs folder
      file:
        src:      /home/drake/franken-printer/configs/
        dest:     /home/pi/configs
        state:    link
        owner:    pi
        group:    drake
        mode:     '0664'

    - name: deploy the main klipper stuff      
      git:
        repo:     https://github.com/KevinOConnor/klipper
        dest:     /home/drake/klipper
        version:  master
        force:    yes

