- name: configure octopi
  hosts:  octopi
  roles:
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_ansible_role    # deploy the ansible repo
    - git_scripts_role    # deploy the scripts repo
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

    - name: deploy the franken-printer configs
      git:
        repo:     https://github.com/educatedCaveman/klipper.git
        dest:     /home/drake/franken-printer
        version:  master
        force:    yes

    - name: copy the printer config to pi
      copy:
        src:        /home/drake/franken-printer/franken-printer.cfg
        dest:       /home/pi/printer.cfg
        owner:      pi
        group:      drake
        mode:       '0750'
        remote_src: yes
        force:      yes

    - name: create the configs folder
      file:
        path:   /home/pi/configs
        state:  directory
        owner:  pi
        group:  drake
        mode:   '0750'

    - name: copy the configs folder to pi
      copy:
        src:        /home/drake/franken-printer/configs/
        dest:       /home/pi/configs/
        owner:      pi
        group:      drake
        mode:       '0750'
        remote_src: yes
        force:      yes

    - name: deploy the main klipper stuff 
      git:
        repo:     https://github.com/KevinOConnor/klipper
        dest:     /home/drake/klipper
        version:  master
        force:    yes

