- name: configure photon-D2
  hosts:  photon_d2
  # roles:
  #   - git_dotfiles_role   # deploy the dotfiles repo
  #   - linux_role          # base linux configs
  #   - client_ssh_keys
  #   - drake_role          # drake home directory permissions
  #   # - rpi_role
  #   - role: telegraf_role
  #     vars:
  #       telegraf_config:  'telegraf_base.conf'
  tasks:

    # - name: create USB folder
    #   file:
    #     path:   /mnt/usb_data
    #     state:  directory

    # - name: mount USB drive
    #   mount:
    #     path:   /mnt/usb_data
    #     src:    /dev/sda1
    #     state:  mounted
    #     boot:   yes #mounted on boot
    #     fstype: vfat

    adapted from: https://magpi.raspberrypi.com/articles/pi-zero-w-smart-usb-flash-drive
    create a file for the USB data to live
    - name: create the USB container file
      community.general.filesize:
        path:       /piusb.bin
        owner:      root
        group:      root
        size:       16GB
        source:     /dev/zero
        blocksize:  1M

    - name: create the filesystem for the usb file
      filesystem:
        dev:    /piusb.bin
        fstype: vfat
        #TODO: not sure how this will work
        opts:   "-F 32 -I"

    # mount the file
    # - test it
    # - test that rerunning the creation command wont overwrite the files

    - name: create the mount directory
      file:
        path:   /mnt/usb_share
        state:  directory

    - name: mount the USB file
      mount:
        boot:   yes #mount at boot
        state:  mounted
        src:    /piusb.bin
        path:   /mnt/usb_share
        fstype: vfat
        opts:   users,umask=000

    # # mass storage mode
    # # setup remote access method
    # #   guide uses samba. I think i might try sftp
    # # USB reconnect
    # # - create a service file