- name: configure Plex
  hosts:  plex
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - client_ssh_keys
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - nfs_backup_role
    - nfs_pics_role
    - nfs_pr0n_role
    - nfs_hegre_role
  tasks:

  # non-standard NFS mounts
  # NFS: Movies
  - name: check for the Movies directory before mounting
    stat: 
      path: /mnt/mobius/Movies
    register: movies_dir
    
  - name: create the mount directory
    file:
      path:     /mnt/mobius/Movies
      state:    directory
      recurse:  yes
    when: not movies_dir.stat.exists

  - name: Mount the Movies NFS share if the mount path exists
    mount:
      src: 192.168.11.2:/mnt/storage_node/Video/Movies
      path: /mnt/mobius/Movies
      fstype: nfs 
      opts: rw,nolock,tcp
      state: mounted

  # NFS: TV Shows
  # careful of the spelling here
  - name: check for the TV Shows directory before mounting
    stat: 
      path: /mnt/mobius/TV-Shows
    register: shows_dir
    
  - name: create the mount directory
    file:
      path:     /mnt/mobius/TV-Shows
      state:    directory
      recurse:  yes
    when: not shows_dir.stat.exists

  - name: Mount the TV Shows NFS share if the mount path exists
    mount:
      src: 192.168.11.2:/mnt/storage_node/Video/TV-shows
      path: /mnt/mobius/TV-Shows
      fstype: nfs 
      opts: rw,nolock,tcp
      state: mounted

  # NFS: Music
  - name: check for the Music directory before mounting
    stat: 
      path: /mnt/mobius/Music
    register: music_dir
  
  - name: create the mount directory
    file:
      path:     /mnt/mobius/Music
      state:    directory
      recurse:  yes
    when: not music_dir.stat.exists

  - name: Mount the Music NFS share if the mount path exists
    mount:
      src: 192.168.11.2:/mnt/storage_node/Music/library
      path: /mnt/mobius/Music
      fstype: nfs 
      opts: rw,nolock,tcp
      state: mounted

  # CRON:
  - name: add backup script to cron
    cron:
      name: plex_backup
      minute: "0"
      hour: "0"
      day:  "1"
      job: "/bin/bash /home/drake/scripts/backup/plex_backup.sh"

  - name: setup TMUX autostart check
    cron:
      name: tmux_run_check
      user: drake
      job: "/bin/bash /home/drake/scripts/cron/tmux_check.sh plex"

  # plex install
  # https://support.plex.tv/articles/235974187-enable-repository-updating-for-supported-linux-server-distributions/
  # - name: Add Plex Repository
  #   apt_repository:
  #     repo: deb https://downloads.plex.tv/repo/deb public main
  #     state: present

  # - name: Add Plex APT Key
  #   apt_key:
  #     url: https://downloads.plex.tv/plex-keys/PlexSign.key
  #     state: present

  # - name: Update apt and install Plex
  #   apt: 
  #     # update_cache: yes
  #     name: 
  #       - plexmediaserver
  #     state: latest

  - name: plex installation
    debug:
      msg:
        - "plex installation is best done manually (its not hard).  follow these instructions:"
        - https://support.plex.tv/articles/235974187-enable-repository-updating-for-supported-linux-server-distributions/

  - name: restoration notes
    debug:
      msg:
        - when re-creating the server, or restoring from backup,
        - you must first manually restore the data.  it also helps
        - to stop the plexmediaserver daemon first.  see the following
        - "link for additional details:"
        - 
        - https://support.plex.tv/articles/201370363-move-an-install-to-another-system/