- name: configure seedbox
  hosts:  seedbox2
  roles:
    - VM_role
    - git_config_role
    - git_dotfiles_role
    - VM_netplan_MTU
    - apt_client_role
    - linux_role
    - client_ssh_keys
    - drake_role
    - nfs_base_role
    - nfs_music_role
    - nfs_video_role
    - nfs_staging_role
    - netdata_role
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
    - docker_role
  vars:
    - repo:        "privateer"
    - src_crypt:   "/home/drake/.git-crypt/{{ repo }}"
    - dest_crypt:  "/home/drake/.git-crypt"
    - key_file:    "{{ dest_crypt }}/{{ repo }}.gpg"
    - docker_path: "/home/drake/{{ repo }}"
  tasks:

    # deploy the repo, and unlock it
    - name:
      git:
        repo: 'https://github.com/educatedCaveman/privateer'
        dest: /home/drake/privateer
        force:  yes

    # # fix directory permissions
    # - name:
    #   file:
    #     path: /home/drake/privateer
    #     state: directory
    #     recurse: yes
    #     owner: drake
    #     group: drake

    - name: ensure the .git-crypt directpry exists
      file:
        path:     "{{ dest_crypt }}"
        state:    directory

    - name: deploy the gpg keys
      copy:
        src:    "{{ src_crypt }}/{{ repo }}.gpg"
        dest:   "{{ key_file }}"
        force:  yes

    - name: unlock the specified repo
      command:  /usr/bin/git-crypt unlock {{ key_file|quote }}
      args:
        chdir:  "{{ docker_path }}"
    
    # start docker stack
    - name: deploy seedbox stack
      docker_compose:
        project_src:    "{{ docker_path }}"
        remove_orphans: yes
        restarted:      yes
