- name: configure singularity
  hosts:  singularity
  roles:
    - LXC_role            # base LXC container config
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - apt_client_role
    - LXC_netplan_MTU     # use the mtu9000 netplan config
    - linux_role          # base linux configs
    - drake_role          # drake home directory permissions
    - nfs_base_role       
    - nfs_backup_role
  tasks:

  - name: setup pihole backup script
    cron:
      name: dev_manager_backup
      minute: "0"
      hour: "2"
      job: "/bin/bash /home/drake/scripts/pihole/pihole_backup.sh"

  - debug:
      msg:  "configuration of pihole must be done manually"

  - debug:
      msg:  "configuration of gravity-sync must be done manually"
