# DNS01 & DNS02 - LXC
- name: configure LXC host(s)
  hosts:  
  - technitium
  roles:
    - LXC_role
    - git_config_role
    - git_dotfiles_role   # deploy the dotfiles repo
    - git_scripts_role
    - linux_role          # base linux configs
    - client_ssh_keys
    - drake_role          # drake home directory permissions
    - keepalived_role
  tasks:


# keepalived master
- name: Master Configuration
  hosts:  dns01
  tasks:
  - name: install primary config file
    ansible.builtin.include_role:
      name: keepalived_role
      tasks_from: dns01.yml


# keepalived secondaries
# DNS02
- name: Secondary Configuration
  hosts:  dns02
  tasks:
  - name: install secondary config file
    ansible.builtin.include_role:
      name: keepalived_role
      tasks_from: dns02.yml

# DNS03
- name: Tertiary Configuration
  hosts:  dns03
  tasks:
  - name: install tertiary config file
    ansible.builtin.include_role:
      name: keepalived_role
      tasks_from: dns03.yml

# DNS04
- name: Quaternary Configuration
  hosts:  dns04
  tasks:
  - name: install quaternary config file
    ansible.builtin.include_role:
      name: keepalived_role
      tasks_from: dns04.yml

# DNS05
- name: Quinternary Configuration
  hosts:  dns05
  tasks:
  - name: install quaternary config file
    ansible.builtin.include_role:
      name: keepalived_role
      tasks_from: dns05.yml


# restart keepalived service
- name: Start and Enable the service
  hosts:  technitium
  tasks:
  - name: keepalived.service
    ansible.builtin.systemd_service:
      name:           keepalived.service
      enabled:        true
      state:          restarted


# Manual steps
- name: Install Technitium
  hosts:  dns01
  tasks:
  - name: Install Technitium (manual)
    ansible.builtin.debug:
        msg:
        - "run the following command in each hosts' shell"
        - "curl -sSL https://download.technitium.com/dns/install.sh | sudo bash"
        