---
- name: configure Unifi Controller
  hosts:  unifi_controller
  roles:
    - VM_role
    - git_dotfiles_role
    # - VM_netplan_MTU
    - apt_client_role
    - linux_role
    - client_ssh_keys
  tasks:

  - name: install prerequisites
    apt:
      name:
        - ca-certificates 
        - openjdk-8-jdk
        - apt-transport-https

  - name: add the unifi repository
    apt_repository:
      repo: 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti'
      filename: 100-ubnt-unifi

  - name: add the unifi gpg key
    apt_key:
      url:  https://dl.ui.com/unifi/unifi-repo.gpg

  - name: update apt cache
    apt:
      update_cache: yes

  - name: install unifi
    apt:
      name: unifi