---
- name: configure Unifi Controller
  hosts:  unifi_controller
  roles:
    - VM_role
    - git_config_role
    - git_dotfiles_role
    - linux_role
    - client_ssh_keys
    - drake_role
    - docker_role
  tasks:

  - name: retrieve unifi-net-app repo
    git:
      repo:   'https://github.com/educatedCaveman/unifi-net-app'
      dest:   /home/drake/unifi
      force:  yes

  - name: manually start unifi
    debug:
      msg:  run "cd unifi && docker compose up"