- name: configure voron
  hosts:  voron
  roles:
    - git_dotfiles_role   # deploy the dotfiles repo
    - linux_role          # base linux configs
    - client_ssh_keys
    - drake_role          # drake home directory permissions
    - role: telegraf_role
      vars:
        telegraf_config:  'telegraf_base.conf'
  tasks:

    # - name: deploy the franken-printer configs
    #   git:
    #     repo:     https://github.com/educatedCaveman/klipper.git
    #     dest:     /home/drake/franken-printer
    #     version:  master
    #     force:    yes

    # - name: copy the printer config to pi
    #   copy:
    #     src:        /home/drake/franken-printer/franken-printer.cfg
    #     dest:       /home/pi/printer.cfg
    #     owner:      pi
    #     group:      drake
    #     mode:       '0750'
    #     remote_src: yes
    #     force:      yes

    # - name: create the configs folder
    #   file:
    #     path:   /home/pi/configs
    #     state:  directory
    #     owner:  pi
    #     group:  drake
    #     mode:   '0750'

    # - name: copy the configs folder to pi
    #   copy:
    #     src:        /home/drake/franken-printer/configs/
    #     dest:       /home/pi/configs/
    #     owner:      pi
    #     group:      drake
    #     mode:       '0750'
    #     remote_src: yes
    #     force:      yes

    # - name: deploy the main klipper stuff 
    #   git:
    #     repo:     https://github.com/KevinOConnor/klipper
    #     dest:     /home/drake/klipper
    #     version:  master
    #     force:    yes

    # Klipper Installation and Update Helper
    - name: deploy KIAUH
      git:
        repo:   https://github.com/th33xitus/kiauh.git
        dest:   /home/pi/kiauh

    - name: create virtual sd card folder
      file:
        path:   /home/pi/gcode_files
        state:  directory
        owner:  pi
        group:  drake
        mode:   '0750'

    - name: set pi home directory permissions
      file:
        path:     /home/pi/
        owner:    pi
        group:    drake
        recurse:  yes

    - name: create drake's link to pi
      file:
        path:   /home/drake/pi/
        state:  link
        src:    /home/pi/

    - name: set drake home directory permissions
      file:
        path:     /home/drake/
        owner:    drake
        group:    drake
        recurse:  yes

    - name: configure klipper and the rest of the things
      debug:
        msg:  "refer to https://github.com/th33xitus/KIAUH"
