- name: configure voron
  hosts:  voron
  roles:
    - git_dotfiles_role   # deploy the dotfiles repo
    - linux_role          # base linux configs
    - client_ssh_keys
    - drake_role          # drake home directory permissions
    - rpi_role
  tasks:

    # Klipper Installation and Update Helper
    - name: deploy KIAUH
      git:
        repo:   https://github.com/th33xitus/kiauh.git
        dest:   /home/pi/kiauh

    - name: create virtual sd card folder
      file:
        path:   /home/pi/gcode_files
        state:  directory
        owner:  pi
        group:  drake
        mode:   '0750'

    - name: set pi home directory permissions
      file:
        path:     /home/pi/
        owner:    pi
        group:    drake
        recurse:  yes

    - name: configure klipper and the rest of the things
      debug:
        msg:  "refer to https://github.com/th33xitus/KIAUH"

    # - name: klipper auto z calibration macro
    #   git:
    #     repo: https://github.com/protoloft/klipper_z_calibration.git
    #     dest: /home/pi/klipper_z_calibration

    # - name: copy python file
    #   copy:
    #     src:    /home/pi/klipper_z_calibration/z_calibration.py
    #     dest:   /home/pi/klipper/klippy/extras/z_calibration.py
    #     owner:  pi
    #     group:  drake
    #     mode:   '0750'
    #     remote_src: yes

    - name: moonraker secrets
      copy:
        src:    /home/drake/.moonraker_secrets.ini
        dest:   /home/pi/.moonraker_secrets.ini
        owner:  pi
        group:  drake
        mode:   '0750'

