---
- name: deploy public keys to authorized_keys files
  hosts: octopi
  ignore_unreachable: yes
  tasks:

    # theseus key
  - name: Set up multiple authorized keys
    authorized_key:
      user: drake
      state: present
      key: '{{ item }}'
    with_file:
      - /home/drake/.ssh/carbon_id_ed25519.pub
      - /home/drake/.ssh/theseus_id_ed25519.pub

    # carbon key