---
- name: deploy klipper repo to octopi
  hosts:  octopi
  tasks:

    - name: deploy klipper configs repo
      git:
        repo:     https://github.com/educatedCaveman/klipper
        dest:     /home/drake/franken-printer
        version:  master
        force:    yes

    - name: copy the printer config to pi
      copy:
        src:        /home/drake/franken-printer/franken-printer.cfg
        dest:       /home/pi/printer.cfg
        owner:      pi
        group:      drake
        mode:       '0750'
        remote_src: yes
        force:      yes

    - name: create the configs folder
      file:
        path:   /home/pi/configs
        state:  directory
        owner:  pi
        group:  drake
        mode:   '0750'

    - name: copy the configs folder to pi
      copy:
        src:        /home/drake/franken-printer/configs/
        dest:       /home/pi/configs/
        owner:      pi
        group:      drake
        mode:       '0750'
        remote_src: yes
        force:      yes

    # Klipper Screen
    # - moonraker
    # - klipperscreen

    # # moonraker klipper config file
    # - name: check for existing default file
    #   stat:
    #     path: /etc/default/klipper
    #   register: default

    # - name: remove the file, if present, and not a link
    #   file:
    #     path: /etc/default/klipper
    #     state:  absent
    #   when:
    #     - default.stat.islnk is defined
    #     - default.stat.islnk == False

    # - name: link custom klipper default file
    #   file:
    #     src:  /home/drake/franken-printer/klipper_default
    #     dest: /etc/default/klipper
    #     state:  link
    #   when: 
    #     - default.stat.islnk is defined
    #     - default.stat.islnk == False

    # # moonraker git
    # - name: deploy moonraker git repo
    #   git: 
    #     repo: https://github.com/Arksine/moonraker.git
    #     dest: /home/pi/moonraker
    #     force:  yes

    # #permissions
    # - name: moonraker folder permissions
    #   file:
    #     path:     /home/pi/moonraker
    #     owner:    pi
    #     group:    drake
    #     mode:     '0750'
    #     recurse:  yes

    # # installation/configuration:
    # - name: installation/configuration
    #   debug:
    #     msg: "see https://moonraker.readthedocs.io/en/latest/installation/ for instructions"

    # # TODO: install custom config      

    # # klipperscreen git
    # - name: deploy klipperscreen git repo
    #   git: 
    #     repo: https://github.com/jordanruthe/KlipperScreen.git
    #     dest: /home/pi/KlipperScreen
    #     force:  yes

    # #permissions
    # - name: KlipperScreen folder permissions
    #   file:
    #     path:     /home/pi/KlipperScreen
    #     owner:    pi
    #     group:    drake
    #     mode:     '0750'
    #     recurse:  yes    

    # # installation/configuration:
    # - name: installation/configuration
    #   debug:
    #     msg: "see https://klipperscreen.readthedocs.io/en/latest/Installation/ for instructions"

    # restart the services
    # klipper
    - name: restart klipper.service
      systemd:
        name: klipper.service
        state:  restarted
        enabled:  yes

    # octoprint
    - name: restart octoprint.service
      systemd:
        name: octoprint.service
        state:  restarted
        enabled:  yes

    # moonraker?
    - name: restart moonraker.service
      systemd:
        name: moonraker.service
        state:  restarted
        enabled:  yes

    # klipperscreen?
    # - name: restart KlipperScreen.service
    #   systemd:
    #     name: KlipperScreen.service
    #     state:  restarted
    #     enabled:  yes