---
- name: deploy klipper repo to voron
  hosts:  voron
  tasks:

    - name: deploy klipper configs to drake user
      git:
        repo:     https://github.com/educatedCaveman/klipper
        dest:     /home/drake/printer_data/config
        version:  voron
        force:    yes

    - name: set permissions
      file:
        path:   /home/drake/printer_data/config
        owner:  drake
        group:  drake
        mode:   '0750'

    # the updating is handled by moonraker
    - name: deploy klipper_z_calibration
      git:
        repo:     https://github.com/protoloft/klipper_z_calibration.git
        dest:     /home/drake/klipper_z_calibration
        update:   no

    
    - name: set permissions
      file:
        path:   /home/drake/klipper_z_calibration
        owner:  drake
        group:  drake
        mode:   '0750'

    # restart the services
    - name: restart all the relevant services
      systemd:
        name:     "{{ item }}.service"
        state:    restarted
        enabled:  yes
      loop:
        - klipper
        # - octoprint
        - moonraker
      #   - mainsail
      #   - klipperscreen
        - crowsnest

# TODO: deploy the KIAUH script

# TODO: handle new moonraker config locations?
# link /home/drake/.moonraker_secrets.ini to /printer_data/moonraker.secrets
# link /home/drake/hu3bert/ to /home/drake/printer_data/config
# link /home/drake/hu3bert/klipper_default to /etc/default/klipper         (may not need this)
# line /home/drake/hu3bert/hu3bert.cfg to /home/drake/hu3bert/printer.cfg
