---
- name: deploy klipper repo to voron
  hosts:  voron
  tasks:

    - name: deploy klipper configs to pi user
      git:
        repo:     https://github.com/educatedCaveman/klipper
        dest:     /home/pi/hu3bert
        version:  voron
        force:    yes

    - name: set permissions
      file:
        path:   /home/pi/hu3bert
        owner:  pi
        group:  drake
        mode:   '0750'

    - name: link the configs to drake user
      file:
        path:   /home/drake/hu3bert
        src:    /home/pi/hu3bert
        state:  link

    - name: create link for klipper printer.cfg
      file:
        path:   /home/pi/hu3bert/printer.cfg
        src:    /home/pi/hu3bert/hu3bert.cfg
        state:  link

    # # restart the services
    # # klipper
    # - name: restart klipper.service
    #   systemd:
    #     name: klipper.service
    #     state:  restarted
    #     enabled:  yes

    # # octoprint
    # - name: restart octoprint.service
    #   systemd:
    #     name: octoprint.service
    #     state:  restarted
    #     enabled:  yes

    # # moonraker?
    # - name: restart moonraker.service
    #   systemd:
    #     name: moonraker.service
    #     state:  restarted
    #     enabled:  yes

    # restart the services
    - name: restart all the relevant services
      systemd:
        name:     "{{ item }}.service"
        state:    restarted
        enabled:  yes
      loop:
        - klipper
        # - octoprint
        - moonraker
      #   - mainsail
      #   - klipperscreen
        - crowsnest

# TODO: deploy the KIAUH script

# TODO: handle new moonraker config locations?
# link /home/pi/.moonraker_secrets.ini to /printer_data/moonraker.secrets
# link /home/pi/hu3bert/ to /home/pi/printer_data/config
# link /home/pi/hu3bert/klipper_default to /etc/default/klipper         (may not need this)
# line /home/pi/hu3bert/hu3bert.cfg to /home/pi/hu3bert/printer.cfg
