---
- name: deploy scripts repo to drake's /home
  hosts:
    - self
    - singularity
  tasks:

    - name: install relevant packages
      apt:
        name:
          - python3-pip

    - name: install 'slack-webhook' pypi package
      pip:
        name: slack-webhook

    - name: create the scripts/ directory
      file:
        path: /home/drake/scripts
        state:  directory
        recurse:  yes

    - name: make sure directory exists
      stat:
        path: /home/drake/scripts
      register: scripts_dir

    - name: deploy scripts repo
      git:
        repo: https://github.com/educatedCaveman/scripts
        dest: /home/drake/scripts
        version:  master
        force:  yes
      when: scripts_dir.stat.exists

    # copy over .zsh_secrets
    - name: copy .zsh_secrets
      copy:
        src:  /home/drake/.zsh_secrets
        dest: /home/drake/.zsh_secrets
        owner:  drake
        group:  drake
        mode: '0644'

    - name: set permissions on directory
      file:
        path: /home/drake/scripts
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake
