---
- name: deploy ansible repo to itself
  hosts:  
    - self
    - dilithium
  vars:
    users:
      - name: drake
        home_dir: /home/drake
      - name: jenkins
        home_dir: /var/lib/jenkins
  tasks:

    # make sure drake has the copybooks
    - name: create the ansible/ directory
      file:
        path: "{{ item.home_dir }}/ansible"
        state:  directory
        recurse:  yes
      loop: "{{ users|flatten(levels=1) }}"

    - name: deploy ansible repo
      git:
        repo: https://github.com/educatedCaveman/ansible
        dest: "{{ item.home_dir }}/ansible"
        version:  master
        force:  yes
      loop: "{{ users|flatten(levels=1) }}"

    - name: set permissions on directory
      file:
        path: "{{ item.home_dir }}/ansible"
        state:  directory
        recurse:  yes
        owner:  "{{ item.name }}"
        group:  "{{ item.name }}"
      loop: "{{ users|flatten(levels=1) }}"
        
