---
- name: deploy scripts repo to drake's /home
  hosts:
    - self
    - singularity
    - dilithium
    - plex
    - moria
    - seedbox
    - apt_mirror
    - doggos
    - nextcloud
    - portainer
  ignore_unreachable: yes
  tasks:

    - name: install relevant packages
      apt:
        name:
          - python3-pip
      ignore_unreachable: yes

    - name: create the scripts/ directory
      file:
        path: /home/drake/scripts
        state:  directory
        recurse:  yes
      ignore_unreachable: yes

    - name: make sure directory exists
      stat:
        path: /home/drake/scripts
      register: scripts_dir
      ignore_unreachable: yes

    - name: deploy scripts repo
      git:
        repo: https://github.com/educatedCaveman/scripts
        dest: /home/drake/scripts
        version:  master
        force:  yes
      when: scripts_dir.stat.exists
      ignore_unreachable: yes

    # copy over .zsh_secrets
    - name: copy .zsh_secrets
      copy:
        src:  /home/drake/.zsh_secrets
        dest: /home/drake/.zsh_secrets
        owner:  drake
        group:  drake
        mode: '0644'
      ignore_unreachable: yes

    - name: set permissions on directory
      file:
        path: /home/drake/scripts
        state:  directory
        recurse:  yes
        owner:  drake
        group:  drake
      ignore_unreachable: yes
