---
- name: deploy klipper repo to octopi
  hosts:  octopi
  tasks:

    - name: deploy klipper configs repo
      git:
        repo:     https://github.com/educatedCaveman/klipper
        dest:     /home/drake/franken-printer
        version:  master
        force:    yes

    - name: copy the printer config to pi
      copy:
        src:        /home/drake/franken-printer/franken-printer.cfg
        dest:       /home/pi/printer.cfg
        owner:      pi
        group:      drake
        mode:       '0750'
        remote_src: yes
        force:      yes

    - name: create the configs folder
      file:
        path:   /home/pi/configs
        state:  directory
        owner:  pi
        group:  drake
        mode:   '0750'

    - name: copy the configs folder to pi
      copy:
        src:        /home/drake/franken-printer/configs/
        dest:       /home/pi/configs/
        owner:      pi
        group:      drake
        mode:       '0750'
        remote_src: yes
        force:      yes

    - name: restart klipper.service
      systemd:
        name: klipper.service
        state:  restarted
        enabled:  yes

