---
- name: configure Ansible/Jenkins
  hosts:  TBD
  vars:
    - cryptpath: /home/drake/.git-crypt/
    - docker_base_path: /docker/docker-compose
  tasks:

    - name: ensure the .git-crypt directpry exists
      file:
        path:   "{{ cryptpath }}"
        state:  directory

    - name: deploy the gpg keys
      copy:
        src:    "{{ cryptpath }}/{{ repo }}.gpg"
        path:   "{{ cryptpath }}/{{ repo }}.gpg"
        force:  yes

    - name: unlock the specified repo
      command:  "/usr/bin/git-crypt unlock {{ cryptpath }}/{{ repo }}.gpg"
        chdir:  "{{ docker_base_path }}/{{ repo }}/"
