---
# tasks file for nfs_staging_role

- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/staging
  register: staging_dir
  
- name: create the mount directory
  file:
    path:     /mnt/mobius/staging
    state:    directory
    recurse:  yes
  when: not staging_dir.stat.exists
  
- name: Mount the staging NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/staging
    path: /mnt/mobius/staging
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
  when: staging_dir.stat.exists
  