---
# tasks file for nfs_books_role
- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/Books
  register: books_dir

- name: create the mount directory
  file:
    path:     /mnt/mobius/Books
    state:    directory
    recurse:  yes
  when: not books_dir.stat.exists

- name: Mount the Books NFS share if the mount path exists
  mount:
    src:    192.168.11.2:/mnt/storage_node/Books
    path:   /mnt/mobius/Books
    fstype: nfs 
    opts:   rw,nolock,tcp
    state:  mounted
