---
# tasks file for VM_role
- name: Update packages
  apt:
    name: '*'
    state: latest

- name: Upgrade packages
  apt:
    upgrade:  safe
    
# make sure we have git installed
- name: Install base packages
  apt:
    name:
      - qemu-guest-agent
      - git
    state:  present

# expand the disk
- name: expand partition
  filesystem:
    fstype:   ext4
    dev:      /dev/vda3
    resizefs: yes


# - name: Read device information (/dev/vda3)
#   community.general.parted: device=/dev/vda3 unit=MiB
#   register: vda3_info

# - name: Extend the partition
#   community.general.parted:
#     device: /dev/vda3
#     number: 3
#     part_end: "100%"
#     resize: true
#     state: present
