---
# tasks file for VM_role
- name: Update packages
  apt:
    name: '*'
    state: latest

- name: Upgrade packages
  apt:
    upgrade:  safe
    
# make sure we have git installed
- name: Install base packages
  apt:
    name:
      - qemu-guest-agent
      - git
    state:  present

# expand the disk
- name: Read device information (/dev/vda3)
  community.general.parted: device=/dev/vda3 unit=MiB
  register: vda3_info

- name: Extend the partition
  community.general.parted:
    device: /dev/vda3
    number: "{{ vda3_info.partitions | length }}"
    part_end: "100%"
    resize: true
    state: present
