---
# stop qbittorrent-nox
- name: stop qibttorrent
  systemd:
    name:     qbittorrent-nox.service
    state:    stopped
    enabled:  yes

# stop openvpn
- name: stop openVPN
  systemd:
    name:     openvpn-client@amsterdam_2.service
    state:    stopped
    enabled:  yes

