---
- name: k3s safe rolling-restart
  # must be run somewhere which has the kubernetes python package
  hosts:  self
  serial: 1
  vars:
    jenkins_kube_config:  /var/lib/jenkins/.kube/config
  tasks:

    # update? (could be all-at-once)
    # cordon
    - name: cordon the node
      kubernetes.core.k8s_drain:
        kubeconfig: "{{jenkins_kube_config}}"
        state:  cordon
        name:   "vespae_3"

    # drain
    - name: drain the node
      kubernetes.core.k8s_drain:
        kubeconfig: "{{jenkins_kube_config}}"
        state:  drain
        name:   "vespae_3"
        force:  yes

    # this won't work...
    # restart, wait
    - name: reboot the node
      ansible.builtin.reboot:
        # default is 600s (10m); 300s should be enough?
        reboot_timeout: 300

    # uncordon
    - name: uncordon the node
      kubernetes.core.k8s_drain:
        kubeconfig: "{{jenkins_kube_config}}"
        state:  uncordon
        name:   "vespae_3"

    # verify cluster state is satisfactory?
