---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Change user password
      user:
        name: root
        update_password: always
        password: "{{ mypass|password_hash('sha512') }}"