---
- name: upgrade/update ubuntu hosts
  # exclude plex while the newer releases are broken
  hosts: ubuntu_debian_hosts
  ignore_unreachable: yes
  ignore_errors:      yes
  tasks:

    - name: update packages
      apt:
        name:     '*'
        state:    latest

    - name: upgrade packages
      apt:
        upgrade:  yes

# rolling restarts
# omit self, because it is what runs the job

- name: rolling restarts, non-HA hosts
  hosts:  ubuntu_debian_hosts:!self:!voron:!k3s
  ignore_unreachable: yes
  ignore_errors:      yes
  tasks:

    - reboot:
        reboot_timeout: 300
