---
- name: upgrade/update ubuntu hosts
  hosts: ubuntu_debian_hosts
  ignore_unreachable: yes
  tasks:

    - name: update packages
      apt:
        name: '*'
        state: latest

    - name: upgrade packages
      apt:
        upgrade:  dist

# rolling restarts
# omit octopi, because it might have a print running

- name: rolling restarts
  hosts:  ubuntu_debian_hosts:!octopi
  serial: 1
  ignore_unreachable: yes
  tasks:

    - reboot:
        reboot_timeout: 300
