- name: update Pi-Hole
  hosts:  pihole
  serial: 1
  tasks:

    - name: update/upgrade packages
      apt:
        update_cache: yes
        upgrade:      yes
        # autoremove:   yes

    - name: test command
      command:
        cmd:  pihole -up
      register: cmd_out

    - name: print command output
      debug:
        var:  cmd_out.stdout_lines
