---
- name: upgrade/update ubuntu hosts
  # exclude plex while the newer releases are broken
  hosts: ubuntu_debian_hosts:!moria
  ignore_unreachable: yes
  ignore_errors:      yes
  tasks:

    - name: update packages
      apt:
        name:     '*'
        state:    latest

    - name: upgrade packages
      apt:
        upgrade:  yes

# rolling restarts
# omit self, because it is what runs the job
# omit moria, because it often has issues being restarted
# - fuckyounvidia.jpg
# omit apt_cache, because it times out

- name: rolling restarts, non-HA hosts
  hosts:  ubuntu_debian_hosts:!self:!moria:!apt_cache:!apt_mirror:!voron
  ignore_unreachable: yes
  ignore_errors:      yes
  tasks:

    - reboot:
        reboot_timeout: 300
