---
- name: upgrade/update ubuntu hosts
  hosts: ubuntu_debian_hosts
  ignore_unreachable: yes
  tasks:

    - name: update packages
      apt:
        name:     '*'
        state:    latest

    - name: upgrade packages
      apt:
        upgrade:  yes

# rolling restarts
# omit octopi, because it might have a print running
# omit self, because it is what runs the job
# omit moria, because it often has issues being restarted
# - fuckyounvidia.jpg
# omit apt_cache, because it times out

- name: rolling restarts, non-HA hosts
  hosts:  ubuntu_debian_hosts:!octopi:!self:!moria:!apt_cache:!apt_mirror
  ignore_unreachable: yes
  tasks:

    - reboot:
        reboot_timeout: 300
