---
#change shell
- name: change to ZSH
    user:
    name: drake
    shell: /usr/bin/zsh

#oh-my-zsh
- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/drake/.oh-my-zsh

#zsh plugin from git:
- name: cloning zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: /home/drake/.oh-my-zsh/custom/plugins/zsh-autosuggestions

# check for dotfiles repo
# the assumption is that if they're there, they were deployed recently
- name: Check if the dotfiles repository is present
  stat:
    path: /home/drake/dotfiles
  register: dotfiles

# ZSH dotfile links:
- name: link .zshrc
  file:
    src: /home/drake/dotfiles/zsh/zshrc
    dest: /home/drake/.zshrc
    state: link
  when: dotfiles.stat.exists

- name: link .zsh_aliases
  file:
    src: /home/drake/dotfiles/zsh/zsh_aliases
    dest: /home/drake/.zsh_aliases
    state: link
  when: dotfiles.stat.exists

- name: link .zsh-theme
  file:
    src: /home/drake/dotfiles/zsh/less-fishy.zsh-theme
    dest: /home/drake/.oh-my-zsh/custom/themes/less-fishy.zsh-theme
    state: link
  when: dotfiles.stat.exists
  