---
# tasks file for nfs_video_role
- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/Video
  register: video_dir
  
- name: create the mount directory
  file:
    path:     /mnt/mobius/Video
    state:    directory
    recurse:  yes
  when: not video_dir.stat.exists

- name: Mount the Video NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/Video
    path: /mnt/mobius/Video
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted