---
- name: configure NFS mounts for DEV docker swarm
  hosts: 
    - dev_swarm_managers
    - dev_swarm_workers
  ignore_unreachable: yes
  tasks:

    - name: make sure we have the nfs-utils...
      apt:
        name: nfs-common
        state: latest

    - name: Mount the Backup share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Backup
        path: /mnt/mobius/Backup
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

    - name: Mount the staging share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/staging/docker/dev
        path: /mnt/mobius/staging
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

    - name: Mount the Docker share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Docker/dev
        path: /mnt/mobius/docker
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

- name: configure NFS mounts for PRD docker swarm
  hosts: 
    - prd_swarm_managers
    - prd_swarm_workers
  ignore_unreachable: yes
  tasks:

    - name: make sure we have the nfs-utils...
      apt:
        name: nfs-common
        state: latest

    - name: Mount the Backup share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Backup
        path: /mnt/mobius/Backup
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

    - name: Mount the staging share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/staging/docker/prd
        path: /mnt/mobius/staging
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted

    - name: Mount the Docker share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Docker/prd
        path: /mnt/mobius/docker
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted