---
- name: configure NFS mount for pihole
  hosts: self
  tasks:

    - name: make sure we have the nfs-utils...
      apt:
        name: nfs-common
        state: latest

    #initial NFS check
    - name: create NFS folder
      file:
        path: /mnt/mobius
        state:  directory

    - name: check for NFS folder
      stat:
        path: /mnt/mobius
      register: mobius

    #mount the Docker NFS share
    - name: Mount the Docker share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Docker
        path: /mnt/mobius/docker
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists

    #mount the staging NFS share
    - name: Mount the staging share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/staging
        path: /mnt/mobius/staging
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists
