---
# tasks file for nfs_docs_role
- name: Mount the Documents NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/Documents
    path: /mnt/mobius/Documents
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
