---
# tasks file for nfs_PVEdata_role
- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/PVE_data
  register: pve_dir
  
- name: create the mount directory
  file:
    path:     /mnt/mobius/PVE_data
    state:    directory
    recurse:  yes
  when: not pve_dir.stat.exists

- name: Mount the PVE_data NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/PVE_data
    path: /mnt/mobius/PVE_data
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
  