---
# main dotfiles linking
- name: deploy pihole dotfiles
  hosts: event_horizon
  tasks:
    # assumes the dotfiles already exist on host
    # eventually remove this:
    #deploy dotfiles repo
    - git:
        repo: 'https://github.com/educatedCaveman/dotfiles.git'
        dest: /home/drake/dotfiles

    # gravity.db
    - name: link gravity.db
      file:
        src:  /home/drake/dotfiles/pihole/gravity.db
        dest: /etc/pihole/gravity.db
        owner:  root
        group:  root
        state:  link

    # custom.list
    - name: link custom.list (local DNS entries)
      file:
        src:  /home/drake/dotfiles/pihole/custom.list
        dest: /etc/pihole/custom.list
        owner:  root
        group:  root
        state:  link

    # dnsmasq (CNAME)
    - name: link dnsmasq CNAMEs
      file:
        src:  /home/drake/dotfiles/pihole/05-pihole-custom-cname.conf
        dest: /etc/dnsmasq.d/05-pihole-custom-cname.conf
        owner:  root
        group:  root
        state:  link
            

# # these are serial in order to prevent DNS from being down 
# # hostfiles links (host-specific)
# - name: link hostsfile, restart DNS, and update gravity (singularity)
#   hosts:  singularity
#   tasks:

#     - name: link singularty hostsfile
#       file:
#         src:  /home/drake/dotfiles/pihole/singularity.hosts
#         dest: /etc/hosts
#         owner:  root
#         group:  root
#         state:  link

#     - name: restart DNS
#       shell:  pihole restartdns

#     - name: update gravity
#       shell:  pihole -g

# # hostfiles links (host-specific)
# - name: link hostsfile, restart DNS, and update gravity (event-horizon)
#   hosts:  event_horizon
#   tasks:

#     - name: link event_horizon hostsfile
#       file:
#         src:  /home/drake/dotfiles/pihole/event-horizon.hosts
#         dest: /etc/hosts
#         owner:  root
#         group:  root
#         state:  link

#     - name: restart DNS
#       shell:  pihole restartdns

#     - name: update gravity
#       shell:  pihole -g
