- name: configure seedbox
  hosts:  seedbox2
  roles:
    - VM_role
    - git_dotfiles_role
    - VM_netplan_MTU
    - apt_client_role
    - linux_role
    - client_ssh_keys
    - drake_role
    - nfs_base_role
    - netdata_role
    # - role: telegraf_role
    #   vars:
    #     telegraf_config:  'telegraf_base.conf'
  tasks:

  # - name: