- name: configure ubuntu hosts
  hosts:  test_host
  roles:
    - LXC_role
    - git_dotfiles_role
    - apt_client_role
    - linux_role
    - gluster_dev_mgr_role
    - drake_role
  tasks:

    - name: check the partitions
      community.general.parted:
        device: /dev/vdb
        unit: MiB
      register: vdb_info

    - name: debug parted info
      debug:
        msg:  "{{ vdb_info }}"
