- name: configure test hosts
  hosts:  test_hosts
  gather_facts: yes
  roles:
    # - LXC_role
    - VM_role
    - git_dotfiles_role
    - VM_netplan_MTU
    - apt_client_role
    - linux_role
    - drake_role
  tasks:

- name: configure test hosts
  hosts:  test_hosts
  gather_facts: yes
  roles:
    - gluster_role
  vars:
    - cluster_name: "swarm_data"
  tasks:

    