---
# this only works when run by jenkins
- name: create the Jenkins/ directory
  file:
    path: /home/drake/Jenkins
    state:  directory
    recurse:  yes

- name: make sure directory exists
  stat:
    path: /home/drake/Jenkins
  register: jenkins_dir

- name: deploy Jenkins repo
  git:
    repo: https://{{USER|urlencode()}}:{{PASS|urlencode()}}@github.com/educatedCaveman/Jenkins.git
    dest: /home/drake/Jenkins
    version:  master
    force:  yes
  when: jenkins_dir.stat.exists
  