---
# tasks file for docker_role
- name: update packages
  apt:
    name: '*'
    state: latest

- name: first round of required packages are installed
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gnupg-agent
      - software-properties-common
    state: present

- name: set keyring permissions
  ansible.builtin.file:
    path:   /etc/apt/keyrings
    owner:  root
    group:  root
    mode:   '0755'
    state:  directory

- name: check for existing Docker GPG key
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: docker_asc

- name: download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    # dest: /tmp/docker.gpg
    dest: /etc/apt/keyrings/docker.asc
  when: docker_asc.stat.exists == False

- name: check for existing Docker repo list
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_list

- name: install repo list
  copy:
    src:  docker.list
    dest: /etc/apt/sources.list.d/docker.list
  when: 
    - docker_list.stat.exists == False
    - ansible_distribution_release == "noble"

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: latest

- name: add drake to the docker group
  user:
    name: drake
    groups:  docker
    append: yes

- name: start and enable docker
  systemd:
    name: docker
    state:  restarted
    enabled:  yes
    