---
# tasks file for docker_role
- name: update packages
  apt:
    name: '*'
    state: latest

- name: first round of required packages are installed
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gnupg-agent
      - software-properties-common
    state: present

- name: set keyring permissions
  ansible.builtin.file:
    path:   /etc/apt/keyrings
    owner:  root
    group:  root
    mode:   '0755'
    state:  directory

- name: check for existing Docker GPG key
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg

- name: download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker.gpg
  when: docker_gpg.stat.exists == False

- name: install Docker GPG key
  ansible.builtin.command:
    cmd:      gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    creates:  /etc/apt/keyrings/docker.gpg

- name: check for existing Docker repo list
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_list

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo:   "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
    file:   docker
    state:  present
  when: docker_list.stat.exists == False

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: latest

- name: add drake to the docker group
  user:
    name: drake
    groups:  docker
    append: yes

- name: start and enable docker
  systemd:
    name: docker
    state:  restarted
    enabled:  yes
    