---
# tasks file for docker_role
- name: update packages
  apt:
    name: '*'
    state: latest

# # Add Docker's official GPG key:
# sudo apt-get update
# sudo apt-get install ca-certificates curl gnupg
# sudo install -m 0755 -d /etc/apt/keyrings
# curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
# sudo chmod a+r /etc/apt/keyrings/docker.gpg

# # Add the repository to Apt sources:
# echo \
#   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
#   $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update

- name: first round of required packages are installed
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - fuse-overlayfs

# - name: install pip packages
#   pip:
#     name: docker

# - name: Add Docker GPG apt Key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

# - name: Add Docker Repository
#   apt_repository:
#     repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#     state: present

- name: Manual installation of docker seems to be the easiest solution
  debug:
    msg: "follow manual installation instructions here"

- name: Update apt and install docker-ce
  apt: 
    # update_cache: yes
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: latest

- name: add drake to the docker group
  user:
    name: drake
    group:  docker
    append: yes

- name: start and enable docker
  systemd:
    name: docker
    state:  restarted
    enabled:  yes
    