vrrp_instance DNS_VI_1 {
  state BACKUP
  interface eth0
  virtual_router_id 55
  priority 60
  advert_int 1
  unicast_src_ip 192.168.12.10
  unicast_peer {
    192.168.12.6
    192.168.12.7
    192.168.12.8
    192.168.12.9
  }

  authentication {
    auth_type PASS
    auth_pass QWGi6u7B
  }

  virtual_ipaddress {
    192.168.12.254/24
  }
}
