vrrp_instance DNS_VI_1 {
  state BACKUP
  interface eth0
  virtual_router_id 55
  priority 70
  advert_int 1
  unicast_src_ip 192.168.11.4
  unicast_peer {
    192.168.11.6
    192.168.11.7
    192.168.11.8
  }

  authentication {
    auth_type PASS
    auth_pass QWGi6u7B
  }

  virtual_ipaddress {
    192.168.11.254/24
  }
}
