---
# tasks file for nfs_pr0n_role
- name: Mount the pr0n NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/pr0n
    path: /mnt/mobius/pr0n
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
