---
# tasks file for nfs_pr0n_role

- name: check for the mount directory before mounting
  stat: 
    path: /mnt/mobius/pr0n
  register: pr0n_dir
  
- name: create the mount directory
  file:
    path:     /mnt/mobius/pr0n
    state:    directory
    recurse:  yes
  when: not pr0n_dir.stat.exists
  
- name: Mount the pr0n NFS share if the mount path exists
  mount:
    src: 192.168.11.2:/mnt/storage_node/pr0n
    path: /mnt/mobius/pr0n
    fstype: nfs 
    opts: rw,nolock,tcp
    state: mounted
  when: pr0n_dir.stat.exists
  