---
- name: configure ubuntu host to use local apt-cache
  hosts: ubuntu_debian_hosts
  tasks:

    # make sure we have git installed
    - name: install git
      apt:
        name: 
          - git

    #deploy dotfiles repo
    - git:
        repo: 'https://github.com/educatedCaveman/dotfiles.git'
        dest: /home/drake/dotfiles
        force:  yes

    # link the config file
    - name: link 00aptproxy
      file:
        src: /home/drake/dotfiles/apt_cache_mirror/00aptproxy
        dest: /etc/apt/apt.conf.d/00aptproxy
        state: link

- name: unlink cache file for apt-mirror and apt-cache
  hosts: 
    - apt_mirror
    - apt_cache
  tasks:

    # link the config file
    - name: unlink 00aptproxy
      file:
        path: /etc/apt/apt.conf.d/00aptproxy
        state:  absent

- name: configure apt-cache
  hosts: apt_cache
  tasks:
    
    - name: install apt-cacher-ng
      apt:
        name: 
          - apt-cacher-ng
        state:  latest

    # make sure apt-cacher-ng.service is running
    - name: ensure apt-cacher-ng.service is running and enabled
      systemd:
        name: apt-cacher-ng.service
        state: restarted
        enabled: yes
