---
- name: configure ubuntu host for docker
  hosts: portainer
  ignore_unreachable: yes
  tasks:
    
    - name: update packages
      apt:
        name: '*'
        state: latest
    
    - name: first round of required packages are installed
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - nfs-common

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt: 
        update_cache: yes
        name: 
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
        state: latest

    - name: add drake to the docker group
      user:
        name: drake
        group:  docker
        append: yes

    #initial NFS check
    - name: create NFS folder
      file:
        path: /mnt/mobius
        state:  directory

    - name: check for NFS folder
      stat:
        path: /mnt/mobius
      register: mobius

    - name: Mount the Backup share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Backup
        path: /mnt/mobius/Backup
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists

- name: Development host mounts
  hosts:  lv_426
  ignore_unreachable: yes
  tasks:

    - name: Mount the staging share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/staging/docker/dev
        path: /mnt/mobius/staging
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists

    - name: Mount the Docker share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Docker/dev
        path: /mnt/mobius/docker
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists

- name: Production host mounts
  hosts:  sevastopol
  ignore_unreachable: yes
  tasks:

    - name: Mount the staging share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/staging/docker/prd
        path: /mnt/mobius/staging
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists

    - name: Mount the Docker share... 
      mount:
        src: 192.168.11.2:/mnt/storage_node/Docker/prd
        path: /mnt/mobius/docker
        fstype: nfs 
        opts: rw,nolock,tcp
        state: mounted
      when: mobius.stat.exists
