---
# link netdata dotfiles
# netdata.conf
- name: remove the existing netdata.conf
  file:
    path: /etc/netdata/netdata.conf
    state:  absent

- name: link netdata.conf
  file:
    src:  /home/drake/dotfiles/netdata/netdata.conf
    dest: /etc/netdata/netdata.conf
    state:  link

# health_alarm_notify.conf
# no longer set to send slack notifications, but doesnt hurt to keep this in place
- name: remove the existing health_alarm_notify.conf
  file:
    path: /etc/netdata/health_alarm_notify.conf
    state:  absent

- name: link health_alarm_notify.conf
  file:
    src:  /home/drake/dotfiles/netdata/health_alarm_notify.conf
    dest: /etc/netdata/health_alarm_notify.conf
    state:  link

# systemd restart and enable netdata
- name: enable and restart netdata
  systemd:
    name: netdata
    state:  restarted
    enabled:  yes