---
- hosts: apis_1
  vars:
    # https://artifacthub.io/packages/helm/unifi/unifi
     helm_chart_url: "oci://ghcr.io/mkilchhofer/unifi-chart/unifi"
  tasks:
    
    # add helm repo
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: unifi
        repo_url: "{{ helm_chart_url }}"

    # install a chart from said repo
    - name: Install Unifi Network Controller Chart
      kubernetes.core.helm:
        name: dev-unifi
        namespace: dev-test
        # chart_ref: bitnami/nginx
        chart_ref: "{{ helm_chart_url }}"

    # install chart
    - name: Install Nginx Chart
      kubernetes.core.helm:
        name: dev-unifi
        namespace: dev-test
        # chart_ref: bitnami/nginx
        chart_ref: "{{ helm_chart_url }}"
        # state: absent
        
    # get info about installed chart
    - name: Gather information about dev-unifi
      kubernetes.core.helm_info:
        name: dev-unifi
        release_namespace: dev-test